export type Country = { code: string; en: string; bn: string };

/** UN member states + observers (195). */
export const COUNTRIES: Country[] = [
  { code: "AF", en: "Afghanistan", bn: "আফগানিস্তান" },
  { code: "AL", en: "Albania", bn: "আলবেনিয়া" },
  { code: "DZ", en: "Algeria", bn: "আলজেরিয়া" },
  { code: "AD", en: "Andorra", bn: "আন্ডোরা" },
  { code: "AO", en: "Angola", bn: "অ্যাঙ্গোলা" },
  { code: "AG", en: "Antigua & Barbuda", bn: "অ্যান্টিগুয়া ও বারবুডা" },
  { code: "AR", en: "Argentina", bn: "আর্জেন্টিনা" },
  { code: "AM", en: "Armenia", bn: "আর্মেনিয়া" },
  { code: "AU", en: "Australia", bn: "অস্ট্রেলিয়া" },
  { code: "AT", en: "Austria", bn: "অস্ট্রিয়া" },
  { code: "AZ", en: "Azerbaijan", bn: "আজারবাইজান" },
  { code: "BS", en: "Bahamas", bn: "বাহামা দ্বীপপুঞ্জ" },
  { code: "BH", en: "Bahrain", bn: "বাহারিন" },
  { code: "BD", en: "Bangladesh", bn: "বাংলাদেশ" },
  { code: "BB", en: "Barbados", bn: "বার্বাডোজ" },
  { code: "BY", en: "Belarus", bn: "বেলারুশ" },
  { code: "BE", en: "Belgium", bn: "বেলজিয়াম" },
  { code: "BZ", en: "Belize", bn: "বেলিজ" },
  { code: "BJ", en: "Benin", bn: "বেনিন" },
  { code: "BT", en: "Bhutan", bn: "ভুটান" },
  { code: "BO", en: "Bolivia", bn: "বলিভিয়া" },
  { code: "BA", en: "Bosnia & Herzegovina", bn: "বসনিয়া ও হার্জেগোভিনা" },
  { code: "BW", en: "Botswana", bn: "বতসোয়ানা" },
  { code: "BR", en: "Brazil", bn: "ব্রাজিল" },
  { code: "BN", en: "Brunei", bn: "ব্রুনেই" },
  { code: "BG", en: "Bulgaria", bn: "বুলগেরিয়া" },
  { code: "BF", en: "Burkina Faso", bn: "বুরকিনা ফাসো" },
  { code: "BI", en: "Burundi", bn: "বুরুন্ডি" },
  { code: "KH", en: "Cambodia", bn: "কম্বোডিয়া" },
  { code: "CM", en: "Cameroon", bn: "ক্যামেরুন" },
  { code: "CA", en: "Canada", bn: "কানাডা" },
  { code: "CV", en: "Cape Verde", bn: "কেপ ভার্দে" },
  { code: "CF", en: "Central African Republic", bn: "মধ্য আফ্রিকার প্রজাতন্ত্র" },
  { code: "TD", en: "Chad", bn: "চাদ" },
  { code: "CL", en: "Chile", bn: "চিলি" },
  { code: "CN", en: "China", bn: "চীন" },
  { code: "CO", en: "Colombia", bn: "কলম্বিয়া" },
  { code: "KM", en: "Comoros", bn: "কমোরোস" },
  { code: "CG", en: "Congo - Brazzaville", bn: "কঙ্গো - ব্রাজাভিল" },
  { code: "CD", en: "Congo - Kinshasa", bn: "কঙ্গো-কিনশাসা" },
  { code: "CR", en: "Costa Rica", bn: "কোস্টারিকা" },
  { code: "CI", en: "Côte d’Ivoire", bn: "কোট ডি‘আইভোর" },
  { code: "HR", en: "Croatia", bn: "ক্রোয়েশিয়া" },
  { code: "CU", en: "Cuba", bn: "কিউবা" },
  { code: "CY", en: "Cyprus", bn: "সাইপ্রাস" },
  { code: "CZ", en: "Czechia", bn: "চেকিয়া" },
  { code: "DK", en: "Denmark", bn: "ডেনমার্ক" },
  { code: "DJ", en: "Djibouti", bn: "জিবুতি" },
  { code: "DM", en: "Dominica", bn: "ডোমিনিকা" },
  { code: "DO", en: "Dominican Republic", bn: "ডোমেনিকান প্রজাতন্ত্র" },
  { code: "EC", en: "Ecuador", bn: "ইকুয়েডর" },
  { code: "EG", en: "Egypt", bn: "মিশর" },
  { code: "SV", en: "El Salvador", bn: "এল সালভেদর" },
  { code: "GQ", en: "Equatorial Guinea", bn: "নিরক্ষীয় গিনি" },
  { code: "ER", en: "Eritrea", bn: "ইরিত্রিয়া" },
  { code: "EE", en: "Estonia", bn: "এস্তোনিয়া" },
  { code: "SZ", en: "Eswatini", bn: "ইসওয়াতিনি" },
  { code: "ET", en: "Ethiopia", bn: "ইথিওপিয়া" },
  { code: "FJ", en: "Fiji", bn: "ফিজি" },
  { code: "FI", en: "Finland", bn: "ফিনল্যান্ড" },
  { code: "FR", en: "France", bn: "ফ্রান্স" },
  { code: "GA", en: "Gabon", bn: "গ্যাবন" },
  { code: "GM", en: "Gambia", bn: "গাম্বিয়া" },
  { code: "GE", en: "Georgia", bn: "জর্জিয়া" },
  { code: "DE", en: "Germany", bn: "জার্মানি" },
  { code: "GH", en: "Ghana", bn: "ঘানা" },
  { code: "GR", en: "Greece", bn: "গ্রীস" },
  { code: "GD", en: "Grenada", bn: "গ্রেনাডা" },
  { code: "GT", en: "Guatemala", bn: "গুয়াতেমালা" },
  { code: "GN", en: "Guinea", bn: "গিনি" },
  { code: "GW", en: "Guinea-Bissau", bn: "গিনি-বিসাউ" },
  { code: "GY", en: "Guyana", bn: "গিয়ানা" },
  { code: "HT", en: "Haiti", bn: "হাইতি" },
  { code: "HN", en: "Honduras", bn: "হন্ডুরাস" },
  { code: "HU", en: "Hungary", bn: "হাঙ্গেরি" },
  { code: "IS", en: "Iceland", bn: "আইসল্যান্ড" },
  { code: "IN", en: "India", bn: "ভারত" },
  { code: "ID", en: "Indonesia", bn: "ইন্দোনেশিয়া" },
  { code: "IR", en: "Iran", bn: "ইরান" },
  { code: "IQ", en: "Iraq", bn: "ইরাক" },
  { code: "IE", en: "Ireland", bn: "আয়ারল্যান্ড" },
  { code: "IL", en: "Israel", bn: "ইজরায়েল" },
  { code: "IT", en: "Italy", bn: "ইতালি" },
  { code: "JM", en: "Jamaica", bn: "জামাইকা" },
  { code: "JP", en: "Japan", bn: "জাপান" },
  { code: "JO", en: "Jordan", bn: "জর্ডন" },
  { code: "KZ", en: "Kazakhstan", bn: "কাজাখস্তান" },
  { code: "KE", en: "Kenya", bn: "কেনিয়া" },
  { code: "KI", en: "Kiribati", bn: "কিরিবাতি" },
  { code: "KW", en: "Kuwait", bn: "কুয়েত" },
  { code: "KG", en: "Kyrgyzstan", bn: "কিরগিজিস্তান" },
  { code: "LA", en: "Laos", bn: "লাওস" },
  { code: "LV", en: "Latvia", bn: "লাটভিয়া" },
  { code: "LB", en: "Lebanon", bn: "লেবানন" },
  { code: "LS", en: "Lesotho", bn: "লেসোথো" },
  { code: "LR", en: "Liberia", bn: "লাইবেরিয়া" },
  { code: "LY", en: "Libya", bn: "লিবিয়া" },
  { code: "LI", en: "Liechtenstein", bn: "লিচেনস্টেইন" },
  { code: "LT", en: "Lithuania", bn: "লিথুয়ানিয়া" },
  { code: "LU", en: "Luxembourg", bn: "লাক্সেমবার্গ" },
  { code: "MG", en: "Madagascar", bn: "মাদাগাস্কার" },
  { code: "MW", en: "Malawi", bn: "মালাউই" },
  { code: "MY", en: "Malaysia", bn: "মালয়েশিয়া" },
  { code: "MV", en: "Maldives", bn: "মালদ্বীপ" },
  { code: "ML", en: "Mali", bn: "মালি" },
  { code: "MT", en: "Malta", bn: "মাল্টা" },
  { code: "MH", en: "Marshall Islands", bn: "মার্শাল দ্বীপপুঞ্জ" },
  { code: "MR", en: "Mauritania", bn: "মরিতানিয়া" },
  { code: "MU", en: "Mauritius", bn: "মরিশাস" },
  { code: "MX", en: "Mexico", bn: "মেক্সিকো" },
  { code: "FM", en: "Micronesia", bn: "মাইক্রোনেশিয়া" },
  { code: "MD", en: "Moldova", bn: "মলডোভা" },
  { code: "MC", en: "Monaco", bn: "মোনাকো" },
  { code: "MN", en: "Mongolia", bn: "মঙ্গোলিয়া" },
  { code: "ME", en: "Montenegro", bn: "মন্টিনিগ্রো" },
  { code: "MA", en: "Morocco", bn: "মোরক্কো" },
  { code: "MZ", en: "Mozambique", bn: "মোজাম্বিক" },
  { code: "MM", en: "Myanmar (Burma)", bn: "মায়ানমার (বার্মা)" },
  { code: "NA", en: "Namibia", bn: "নামিবিয়া" },
  { code: "NR", en: "Nauru", bn: "নাউরু" },
  { code: "NP", en: "Nepal", bn: "নেপাল" },
  { code: "NL", en: "Netherlands", bn: "নেদারল্যান্ডস" },
  { code: "NZ", en: "New Zealand", bn: "নিউজিল্যান্ড" },
  { code: "NI", en: "Nicaragua", bn: "নিকারাগুয়া" },
  { code: "NE", en: "Niger", bn: "নাইজার" },
  { code: "NG", en: "Nigeria", bn: "নাইজেরিয়া" },
  { code: "KP", en: "North Korea", bn: "উত্তর কোরিয়া" },
  { code: "MK", en: "North Macedonia", bn: "উত্তর ম্যাসেডোনিয়া" },
  { code: "NO", en: "Norway", bn: "নরওয়ে" },
  { code: "OM", en: "Oman", bn: "ওমান" },
  { code: "PK", en: "Pakistan", bn: "পাকিস্তান" },
  { code: "PW", en: "Palau", bn: "পালাউ" },
  { code: "PS", en: "Palestinian Territories", bn: "প্যালেস্টাইন ভূখণ্ড" },
  { code: "PA", en: "Panama", bn: "পানামা" },
  { code: "PG", en: "Papua New Guinea", bn: "পাপুয়া নিউ গিনি" },
  { code: "PY", en: "Paraguay", bn: "প্যারাগুয়ে" },
  { code: "PE", en: "Peru", bn: "পেরু" },
  { code: "PH", en: "Philippines", bn: "ফিলিপাইন" },
  { code: "PL", en: "Poland", bn: "পোল্যান্ড" },
  { code: "PT", en: "Portugal", bn: "পর্তুগাল" },
  { code: "QA", en: "Qatar", bn: "কাতার" },
  { code: "RO", en: "Romania", bn: "রোমানিয়া" },
  { code: "RU", en: "Russia", bn: "রাশিয়া" },
  { code: "RW", en: "Rwanda", bn: "রুয়ান্ডা" },
  { code: "WS", en: "Samoa", bn: "সামোয়া" },
  { code: "SM", en: "San Marino", bn: "সান মারিনো" },
  { code: "ST", en: "São Tomé & Príncipe", bn: "সাওটোমা ও প্রিন্সিপি" },
  { code: "SA", en: "Saudi Arabia", bn: "সৌদি আরব" },
  { code: "SN", en: "Senegal", bn: "সেনেগাল" },
  { code: "RS", en: "Serbia", bn: "সার্বিয়া" },
  { code: "SC", en: "Seychelles", bn: "সিসিলি" },
  { code: "SL", en: "Sierra Leone", bn: "সিয়েরা লিওন" },
  { code: "SG", en: "Singapore", bn: "সিঙ্গাপুর" },
  { code: "SK", en: "Slovakia", bn: "স্লোভাকিয়া" },
  { code: "SI", en: "Slovenia", bn: "স্লোভানিয়া" },
  { code: "SB", en: "Solomon Islands", bn: "সলোমন দ্বীপপুঞ্জ" },
  { code: "SO", en: "Somalia", bn: "সোমালিয়া" },
  { code: "ZA", en: "South Africa", bn: "দক্ষিণ আফ্রিকা" },
  { code: "KR", en: "South Korea", bn: "দক্ষিণ কোরিয়া" },
  { code: "SS", en: "South Sudan", bn: "দক্ষিণ সুদান" },
  { code: "ES", en: "Spain", bn: "স্পেন" },
  { code: "LK", en: "Sri Lanka", bn: "শ্রীলঙ্কা" },
  { code: "KN", en: "St. Kitts & Nevis", bn: "সেন্ট কিটস ও নেভিস" },
  { code: "LC", en: "St. Lucia", bn: "সেন্ট লুসিয়া" },
  { code: "VC", en: "St. Vincent & Grenadines", bn: "সেন্ট ভিনসেন্ট ও গ্রেনাডিনস" },
  { code: "SD", en: "Sudan", bn: "সুদান" },
  { code: "SR", en: "Suriname", bn: "সুরিনাম" },
  { code: "SE", en: "Sweden", bn: "সুইডেন" },
  { code: "CH", en: "Switzerland", bn: "সুইজারল্যান্ড" },
  { code: "SY", en: "Syria", bn: "সিরিয়া" },
  { code: "TJ", en: "Tajikistan", bn: "তাজিকিস্তান" },
  { code: "TZ", en: "Tanzania", bn: "তাঞ্জানিয়া" },
  { code: "TH", en: "Thailand", bn: "থাইল্যান্ড" },
  { code: "TL", en: "Timor-Leste", bn: "তিমুর-লেস্তে" },
  { code: "TG", en: "Togo", bn: "টোগো" },
  { code: "TO", en: "Tonga", bn: "টোঙ্গা" },
  { code: "TT", en: "Trinidad & Tobago", bn: "ত্রিনিনাদ ও টোব্যাগো" },
  { code: "TN", en: "Tunisia", bn: "তিউনিসিয়া" },
  { code: "TR", en: "Türkiye", bn: "তুরস্ক" },
  { code: "TM", en: "Turkmenistan", bn: "তুর্কমেনিস্তান" },
  { code: "TV", en: "Tuvalu", bn: "টুভালু" },
  { code: "UG", en: "Uganda", bn: "উগান্ডা" },
  { code: "UA", en: "Ukraine", bn: "ইউক্রেন" },
  { code: "AE", en: "United Arab Emirates", bn: "সংযুক্ত আরব আমিরাত" },
  { code: "GB", en: "United Kingdom", bn: "যুক্তরাজ্য" },
  { code: "US", en: "United States", bn: "মার্কিন যুক্তরাষ্ট্র" },
  { code: "UY", en: "Uruguay", bn: "উরুগুয়ে" },
  { code: "UZ", en: "Uzbekistan", bn: "উজবেকিস্তান" },
  { code: "VU", en: "Vanuatu", bn: "ভানুয়াটু" },
  { code: "VA", en: "Vatican City", bn: "ভ্যাটিকান সিটি" },
  { code: "VE", en: "Venezuela", bn: "ভেনেজুয়েলা" },
  { code: "VN", en: "Vietnam", bn: "ভিয়েতনাম" },
  { code: "YE", en: "Yemen", bn: "ইয়েমেন" },
  { code: "ZM", en: "Zambia", bn: "জাম্বিয়া" },
  { code: "ZW", en: "Zimbabwe", bn: "জিম্বাবোয়ে" },
];
