import type { LanguageCode } from "./i18n-50-languages";

/**
 * Core UI vocabulary translated into every supported language.
 *
 * These entries are merged on top of the base (bn/en) dictionary in i18n.tsx.
 * Any key missing for a language falls back to English, then Bengali, so the
 * app never renders a blank label.
 */
export type CoreTranslations = Partial<Record<LanguageCode, Record<string, string>>>;

export const CORE_TRANSLATIONS: CoreTranslations = {
  hi: { next: "आगे", skip: "छोड़ें", back: "वापस", prev: "पीछे", done: "पूर्ण", add: "जोड़ें", generate: "रेसिपी बनाएँ", generating: "रेसिपी बन रही है…", suggestions: "सुझाव", recipes: "आपकी रेसिपी", ingredients: "सामग्री", steps: "विधि", minutes: "मिनट", preferences: "प्राथमिकताएँ", share: "साझा करें", download: "डाउनलोड", saved: "सहेजा गया", send: "भेजें", enable: "चालू करें", disable: "बंद करें", selectLanguage: "अपनी भाषा चुनें", searchLanguage: "भाषा खोजें", confirmSelection: "चयन पूरा करें" },
  es: { next: "Siguiente", skip: "Omitir", back: "Atrás", prev: "Atrás", done: "Listo", add: "Añadir", generate: "Generar recetas", generating: "Preparando recetas…", suggestions: "Sugerencias", recipes: "Tus recetas", ingredients: "Ingredientes", steps: "Pasos", minutes: "min", preferences: "Preferencias", share: "Compartir", download: "Descargar", saved: "Guardado", send: "Enviar", enable: "Activar", disable: "Desactivar", selectLanguage: "Elige tu idioma", searchLanguage: "Buscar idioma", confirmSelection: "Confirmar selección" },
  fr: { next: "Suivant", skip: "Passer", back: "Retour", prev: "Retour", done: "Terminé", add: "Ajouter", generate: "Générer des recettes", generating: "Préparation des recettes…", suggestions: "Suggestions", recipes: "Vos recettes", ingredients: "Ingrédients", steps: "Étapes", minutes: "min", preferences: "Préférences", share: "Partager", download: "Télécharger", saved: "Enregistré", send: "Envoyer", enable: "Activer", disable: "Désactiver", selectLanguage: "Choisissez votre langue", searchLanguage: "Rechercher une langue", confirmSelection: "Confirmer la sélection" },
  de: { next: "Weiter", skip: "Überspringen", back: "Zurück", prev: "Zurück", done: "Fertig", add: "Hinzufügen", generate: "Rezepte erstellen", generating: "Rezepte werden erstellt…", suggestions: "Vorschläge", recipes: "Deine Rezepte", ingredients: "Zutaten", steps: "Schritte", minutes: "Min", preferences: "Einstellungen", share: "Teilen", download: "Herunterladen", saved: "Gespeichert", send: "Senden", enable: "Aktivieren", disable: "Deaktivieren", selectLanguage: "Wähle deine Sprache", searchLanguage: "Sprache suchen", confirmSelection: "Auswahl bestätigen" },
  pt: { next: "Próximo", skip: "Pular", back: "Voltar", prev: "Voltar", done: "Concluir", add: "Adicionar", generate: "Gerar receitas", generating: "Preparando receitas…", suggestions: "Sugestões", recipes: "Suas receitas", ingredients: "Ingredientes", steps: "Modo de preparo", minutes: "min", preferences: "Preferências", share: "Compartilhar", download: "Baixar", saved: "Salvo", send: "Enviar", enable: "Ativar", disable: "Desativar", selectLanguage: "Escolha seu idioma", searchLanguage: "Buscar idioma", confirmSelection: "Confirmar seleção" },
  it: { next: "Avanti", skip: "Salta", back: "Indietro", prev: "Indietro", done: "Fatto", add: "Aggiungi", generate: "Genera ricette", generating: "Sto preparando le ricette…", suggestions: "Suggerimenti", recipes: "Le tue ricette", ingredients: "Ingredienti", steps: "Preparazione", minutes: "min", preferences: "Preferenze", share: "Condividi", download: "Scarica", saved: "Salvato", send: "Invia", enable: "Attiva", disable: "Disattiva", selectLanguage: "Scegli la tua lingua", searchLanguage: "Cerca lingua", confirmSelection: "Conferma selezione" },
  nl: { next: "Volgende", skip: "Overslaan", back: "Terug", prev: "Terug", done: "Klaar", add: "Toevoegen", generate: "Recepten maken", generating: "Recepten worden gemaakt…", suggestions: "Suggesties", recipes: "Jouw recepten", ingredients: "Ingrediënten", steps: "Stappen", minutes: "min", preferences: "Voorkeuren", share: "Delen", download: "Downloaden", saved: "Opgeslagen", send: "Versturen", enable: "Inschakelen", disable: "Uitschakelen", selectLanguage: "Kies je taal", searchLanguage: "Taal zoeken", confirmSelection: "Selectie bevestigen" },
  ru: { next: "Далее", skip: "Пропустить", back: "Назад", prev: "Назад", done: "Готово", add: "Добавить", generate: "Создать рецепты", generating: "Готовим рецепты…", suggestions: "Подсказки", recipes: "Ваши рецепты", ingredients: "Ингредиенты", steps: "Шаги", minutes: "мин", preferences: "Настройки", share: "Поделиться", download: "Скачать", saved: "Сохранено", send: "Отправить", enable: "Включить", disable: "Выключить", selectLanguage: "Выберите язык", searchLanguage: "Поиск языка", confirmSelection: "Подтвердить выбор" },
  ar: { next: "التالي", skip: "تخطٍّ", back: "رجوع", prev: "رجوع", done: "تم", add: "إضافة", generate: "إنشاء وصفات", generating: "جارٍ إعداد الوصفات…", suggestions: "اقتراحات", recipes: "وصفاتك", ingredients: "المكونات", steps: "الخطوات", minutes: "دقيقة", preferences: "التفضيلات", share: "مشاركة", download: "تنزيل", saved: "تم الحفظ", send: "إرسال", enable: "تفعيل", disable: "إيقاف", selectLanguage: "اختر لغتك", searchLanguage: "ابحث عن لغة", confirmSelection: "تأكيد الاختيار" },
  "zh-Hans": { next: "下一步", skip: "跳过", back: "返回", prev: "上一步", done: "完成", add: "添加", generate: "生成菜谱", generating: "正在生成菜谱…", suggestions: "建议", recipes: "你的菜谱", ingredients: "食材", steps: "步骤", minutes: "分钟", preferences: "偏好设置", share: "分享", download: "下载", saved: "已保存", send: "发送", enable: "开启", disable: "关闭", selectLanguage: "选择你的语言", searchLanguage: "搜索语言", confirmSelection: "确认选择" },
  "zh-Hant": { next: "下一步", skip: "略過", back: "返回", prev: "上一步", done: "完成", add: "新增", generate: "產生食譜", generating: "正在產生食譜…", suggestions: "建議", recipes: "你的食譜", ingredients: "食材", steps: "步驟", minutes: "分鐘", preferences: "偏好設定", share: "分享", download: "下載", saved: "已儲存", send: "傳送", enable: "開啟", disable: "關閉", selectLanguage: "選擇你的語言", searchLanguage: "搜尋語言", confirmSelection: "確認選擇" },
  ja: { next: "次へ", skip: "スキップ", back: "戻る", prev: "前へ", done: "完了", add: "追加", generate: "レシピを作成", generating: "レシピを作成中…", suggestions: "提案", recipes: "あなたのレシピ", ingredients: "材料", steps: "手順", minutes: "分", preferences: "設定", share: "共有", download: "ダウンロード", saved: "保存しました", send: "送信", enable: "有効にする", disable: "無効にする", selectLanguage: "言語を選択", searchLanguage: "言語を検索", confirmSelection: "選択を確定" },
  ko: { next: "다음", skip: "건너뛰기", back: "뒤로", prev: "이전", done: "완료", add: "추가", generate: "레시피 만들기", generating: "레시피 만드는 중…", suggestions: "추천", recipes: "내 레시피", ingredients: "재료", steps: "조리 순서", minutes: "분", preferences: "환경설정", share: "공유", download: "다운로드", saved: "저장됨", send: "보내기", enable: "켜기", disable: "끄기", selectLanguage: "언어를 선택하세요", searchLanguage: "언어 검색", confirmSelection: "선택 완료" },
  th: { next: "ถัดไป", skip: "ข้าม", back: "ย้อนกลับ", prev: "ก่อนหน้า", done: "เสร็จสิ้น", add: "เพิ่ม", generate: "สร้างสูตรอาหาร", generating: "กำลังสร้างสูตร…", suggestions: "ข้อเสนอแนะ", recipes: "สูตรของคุณ", ingredients: "ส่วนผสม", steps: "ขั้นตอน", minutes: "นาที", preferences: "การตั้งค่า", share: "แชร์", download: "ดาวน์โหลด", saved: "บันทึกแล้ว", send: "ส่ง", enable: "เปิด", disable: "ปิด", selectLanguage: "เลือกภาษาของคุณ", searchLanguage: "ค้นหาภาษา", confirmSelection: "ยืนยันการเลือก" },
  vi: { next: "Tiếp theo", skip: "Bỏ qua", back: "Quay lại", prev: "Trước", done: "Xong", add: "Thêm", generate: "Tạo công thức", generating: "Đang tạo công thức…", suggestions: "Gợi ý", recipes: "Công thức của bạn", ingredients: "Nguyên liệu", steps: "Các bước", minutes: "phút", preferences: "Tùy chọn", share: "Chia sẻ", download: "Tải xuống", saved: "Đã lưu", send: "Gửi", enable: "Bật", disable: "Tắt", selectLanguage: "Chọn ngôn ngữ của bạn", searchLanguage: "Tìm ngôn ngữ", confirmSelection: "Xác nhận lựa chọn" },
  id: { next: "Berikutnya", skip: "Lewati", back: "Kembali", prev: "Sebelumnya", done: "Selesai", add: "Tambah", generate: "Buat resep", generating: "Membuat resep…", suggestions: "Saran", recipes: "Resep Anda", ingredients: "Bahan", steps: "Langkah", minutes: "menit", preferences: "Preferensi", share: "Bagikan", download: "Unduh", saved: "Tersimpan", send: "Kirim", enable: "Aktifkan", disable: "Nonaktifkan", selectLanguage: "Pilih bahasa Anda", searchLanguage: "Cari bahasa", confirmSelection: "Konfirmasi pilihan" },
  tl: { next: "Susunod", skip: "Laktawan", back: "Bumalik", prev: "Nakaraan", done: "Tapos", add: "Idagdag", generate: "Gumawa ng recipe", generating: "Gumagawa ng recipe…", suggestions: "Mga mungkahi", recipes: "Iyong mga recipe", ingredients: "Sangkap", steps: "Mga hakbang", minutes: "min", preferences: "Kagustuhan", share: "Ibahagi", download: "I-download", saved: "Nai-save", send: "Ipadala", enable: "Paganahin", disable: "Huwag paganahin", selectLanguage: "Piliin ang iyong wika", searchLanguage: "Maghanap ng wika", confirmSelection: "Kumpirmahin ang pinili" },
  tr: { next: "İleri", skip: "Atla", back: "Geri", prev: "Geri", done: "Bitti", add: "Ekle", generate: "Tarif oluştur", generating: "Tarifler hazırlanıyor…", suggestions: "Öneriler", recipes: "Tarifleriniz", ingredients: "Malzemeler", steps: "Adımlar", minutes: "dk", preferences: "Tercihler", share: "Paylaş", download: "İndir", saved: "Kaydedildi", send: "Gönder", enable: "Etkinleştir", disable: "Devre dışı bırak", selectLanguage: "Dilinizi seçin", searchLanguage: "Dil ara", confirmSelection: "Seçimi onayla" },
  el: { next: "Επόμενο", skip: "Παράλειψη", back: "Πίσω", prev: "Πίσω", done: "Τέλος", add: "Προσθήκη", generate: "Δημιουργία συνταγών", generating: "Δημιουργία συνταγών…", suggestions: "Προτάσεις", recipes: "Οι συνταγές σου", ingredients: "Υλικά", steps: "Βήματα", minutes: "λεπτά", preferences: "Προτιμήσεις", share: "Κοινοποίηση", download: "Λήψη", saved: "Αποθηκεύτηκε", send: "Αποστολή", enable: "Ενεργοποίηση", disable: "Απενεργοποίηση", selectLanguage: "Επίλεξε τη γλώσσα σου", searchLanguage: "Αναζήτηση γλώσσας", confirmSelection: "Επιβεβαίωση επιλογής" },
  sv: { next: "Nästa", skip: "Hoppa över", back: "Tillbaka", prev: "Tillbaka", done: "Klar", add: "Lägg till", generate: "Skapa recept", generating: "Skapar recept…", suggestions: "Förslag", recipes: "Dina recept", ingredients: "Ingredienser", steps: "Steg", minutes: "min", preferences: "Inställningar", share: "Dela", download: "Ladda ner", saved: "Sparat", send: "Skicka", enable: "Aktivera", disable: "Inaktivera", selectLanguage: "Välj ditt språk", searchLanguage: "Sök språk", confirmSelection: "Bekräfta val" },
  no: { next: "Neste", skip: "Hopp over", back: "Tilbake", prev: "Tilbake", done: "Ferdig", add: "Legg til", generate: "Lag oppskrifter", generating: "Lager oppskrifter…", suggestions: "Forslag", recipes: "Dine oppskrifter", ingredients: "Ingredienser", steps: "Trinn", minutes: "min", preferences: "Innstillinger", share: "Del", download: "Last ned", saved: "Lagret", send: "Send", enable: "Slå på", disable: "Slå av", selectLanguage: "Velg språket ditt", searchLanguage: "Søk etter språk", confirmSelection: "Bekreft valg" },
  da: { next: "Næste", skip: "Spring over", back: "Tilbage", prev: "Tilbage", done: "Færdig", add: "Tilføj", generate: "Lav opskrifter", generating: "Laver opskrifter…", suggestions: "Forslag", recipes: "Dine opskrifter", ingredients: "Ingredienser", steps: "Trin", minutes: "min", preferences: "Indstillinger", share: "Del", download: "Download", saved: "Gemt", send: "Send", enable: "Slå til", disable: "Slå fra", selectLanguage: "Vælg dit sprog", searchLanguage: "Søg sprog", confirmSelection: "Bekræft valg" },
  fi: { next: "Seuraava", skip: "Ohita", back: "Takaisin", prev: "Takaisin", done: "Valmis", add: "Lisää", generate: "Luo reseptejä", generating: "Luodaan reseptejä…", suggestions: "Ehdotukset", recipes: "Reseptisi", ingredients: "Ainekset", steps: "Vaiheet", minutes: "min", preferences: "Asetukset", share: "Jaa", download: "Lataa", saved: "Tallennettu", send: "Lähetä", enable: "Ota käyttöön", disable: "Poista käytöstä", selectLanguage: "Valitse kielesi", searchLanguage: "Hae kieltä", confirmSelection: "Vahvista valinta" },
  pl: { next: "Dalej", skip: "Pomiń", back: "Wstecz", prev: "Wstecz", done: "Gotowe", add: "Dodaj", generate: "Generuj przepisy", generating: "Tworzę przepisy…", suggestions: "Propozycje", recipes: "Twoje przepisy", ingredients: "Składniki", steps: "Kroki", minutes: "min", preferences: "Preferencje", share: "Udostępnij", download: "Pobierz", saved: "Zapisano", send: "Wyślij", enable: "Włącz", disable: "Wyłącz", selectLanguage: "Wybierz swój język", searchLanguage: "Szukaj języka", confirmSelection: "Potwierdź wybór" },
  cs: { next: "Další", skip: "Přeskočit", back: "Zpět", prev: "Zpět", done: "Hotovo", add: "Přidat", generate: "Vytvořit recepty", generating: "Vytvářím recepty…", suggestions: "Návrhy", recipes: "Vaše recepty", ingredients: "Suroviny", steps: "Postup", minutes: "min", preferences: "Předvolby", share: "Sdílet", download: "Stáhnout", saved: "Uloženo", send: "Odeslat", enable: "Zapnout", disable: "Vypnout", selectLanguage: "Vyberte svůj jazyk", searchLanguage: "Hledat jazyk", confirmSelection: "Potvrdit výběr" },
  hu: { next: "Tovább", skip: "Kihagyás", back: "Vissza", prev: "Vissza", done: "Kész", add: "Hozzáadás", generate: "Receptek készítése", generating: "Receptek készülnek…", suggestions: "Javaslatok", recipes: "A receptjeid", ingredients: "Hozzávalók", steps: "Lépések", minutes: "perc", preferences: "Beállítások", share: "Megosztás", download: "Letöltés", saved: "Mentve", send: "Küldés", enable: "Bekapcsolás", disable: "Kikapcsolás", selectLanguage: "Válaszd ki a nyelved", searchLanguage: "Nyelv keresése", confirmSelection: "Választás megerősítése" },
  ro: { next: "Înainte", skip: "Sari peste", back: "Înapoi", prev: "Înapoi", done: "Gata", add: "Adaugă", generate: "Generează rețete", generating: "Se creează rețetele…", suggestions: "Sugestii", recipes: "Rețetele tale", ingredients: "Ingrediente", steps: "Pași", minutes: "min", preferences: "Preferințe", share: "Distribuie", download: "Descarcă", saved: "Salvat", send: "Trimite", enable: "Activează", disable: "Dezactivează", selectLanguage: "Alege-ți limba", searchLanguage: "Caută limba", confirmSelection: "Confirmă selecția" },
  bg: { next: "Напред", skip: "Пропусни", back: "Назад", prev: "Назад", done: "Готово", add: "Добави", generate: "Създай рецепти", generating: "Създаване на рецепти…", suggestions: "Предложения", recipes: "Твоите рецепти", ingredients: "Съставки", steps: "Стъпки", minutes: "мин", preferences: "Предпочитания", share: "Сподели", download: "Изтегли", saved: "Запазено", send: "Изпрати", enable: "Включи", disable: "Изключи", selectLanguage: "Избери своя език", searchLanguage: "Търси език", confirmSelection: "Потвърди избора" },
  hr: { next: "Dalje", skip: "Preskoči", back: "Natrag", prev: "Natrag", done: "Gotovo", add: "Dodaj", generate: "Izradi recepte", generating: "Izrađujem recepte…", suggestions: "Prijedlozi", recipes: "Tvoji recepti", ingredients: "Sastojci", steps: "Koraci", minutes: "min", preferences: "Postavke", share: "Podijeli", download: "Preuzmi", saved: "Spremljeno", send: "Pošalji", enable: "Uključi", disable: "Isključi", selectLanguage: "Odaberi svoj jezik", searchLanguage: "Traži jezik", confirmSelection: "Potvrdi odabir" },
  sr: { next: "Даље", skip: "Прескочи", back: "Назад", prev: "Назад", done: "Готово", add: "Додај", generate: "Направи рецепте", generating: "Правим рецепте…", suggestions: "Предлози", recipes: "Твоји рецепти", ingredients: "Састојци", steps: "Кораци", minutes: "мин", preferences: "Подешавања", share: "Подели", download: "Преузми", saved: "Сачувано", send: "Пошаљи", enable: "Укључи", disable: "Искључи", selectLanguage: "Изабери свој језик", searchLanguage: "Претражи језик", confirmSelection: "Потврди избор" },
  sl: { next: "Naprej", skip: "Preskoči", back: "Nazaj", prev: "Nazaj", done: "Končano", add: "Dodaj", generate: "Ustvari recepte", generating: "Ustvarjam recepte…", suggestions: "Predlogi", recipes: "Tvoji recepti", ingredients: "Sestavine", steps: "Koraki", minutes: "min", preferences: "Nastavitve", share: "Deli", download: "Prenesi", saved: "Shranjeno", send: "Pošlji", enable: "Vklopi", disable: "Izklopi", selectLanguage: "Izberi svoj jezik", searchLanguage: "Išči jezik", confirmSelection: "Potrdi izbiro" },
  ur: { next: "آگے", skip: "چھوڑیں", back: "واپس", prev: "پیچھے", done: "مکمل", add: "شامل کریں", generate: "ترکیبیں بنائیں", generating: "ترکیبیں بن رہی ہیں…", suggestions: "تجاویز", recipes: "آپ کی ترکیبیں", ingredients: "اجزاء", steps: "ترکیب", minutes: "منٹ", preferences: "ترجیحات", share: "شیئر کریں", download: "ڈاؤن لوڈ", saved: "محفوظ", send: "بھیجیں", enable: "فعال کریں", disable: "بند کریں", selectLanguage: "اپنی زبان منتخب کریں", searchLanguage: "زبان تلاش کریں", confirmSelection: "انتخاب مکمل کریں" },
  pa: { next: "ਅੱਗੇ", skip: "ਛੱਡੋ", back: "ਵਾਪਸ", prev: "ਪਿੱਛੇ", done: "ਹੋ ਗਿਆ", add: "ਸ਼ਾਮਲ ਕਰੋ", generate: "ਰੈਸਿਪੀ ਬਣਾਓ", generating: "ਰੈਸਿਪੀ ਬਣ ਰਹੀ ਹੈ…", suggestions: "ਸੁਝਾਅ", recipes: "ਤੁਹਾਡੀਆਂ ਰੈਸਿਪੀਆਂ", ingredients: "ਸਮੱਗਰੀ", steps: "ਵਿਧੀ", minutes: "ਮਿੰਟ", preferences: "ਤਰਜੀਹਾਂ", share: "ਸਾਂਝਾ ਕਰੋ", download: "ਡਾਊਨਲੋਡ", saved: "ਸੰਭਾਲਿਆ", send: "ਭੇਜੋ", enable: "ਚਾਲੂ ਕਰੋ", disable: "ਬੰਦ ਕਰੋ", selectLanguage: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ", searchLanguage: "ਭਾਸ਼ਾ ਖੋਜੋ", confirmSelection: "ਚੋਣ ਪੂਰੀ ਕਰੋ" },
  gu: { next: "આગળ", skip: "છોડો", back: "પાછળ", prev: "પાછળ", done: "પૂર્ણ", add: "ઉમેરો", generate: "રેસિપી બનાવો", generating: "રેસિપી બની રહી છે…", suggestions: "સૂચનો", recipes: "તમારી રેસિપી", ingredients: "સામગ્રી", steps: "રીત", minutes: "મિનિટ", preferences: "પસંદગીઓ", share: "શેર કરો", download: "ડાઉનલોડ", saved: "સાચવ્યું", send: "મોકલો", enable: "ચાલુ કરો", disable: "બંધ કરો", selectLanguage: "તમારી ભાષા પસંદ કરો", searchLanguage: "ભાષા શોધો", confirmSelection: "પસંદગી પૂર્ણ કરો" },
  mr: { next: "पुढे", skip: "वगळा", back: "मागे", prev: "मागे", done: "पूर्ण", add: "जोडा", generate: "पाककृती तयार करा", generating: "पाककृती तयार होत आहे…", suggestions: "सूचना", recipes: "तुमच्या पाककृती", ingredients: "साहित्य", steps: "कृती", minutes: "मिनिटे", preferences: "प्राधान्ये", share: "शेअर करा", download: "डाउनलोड", saved: "जतन केले", send: "पाठवा", enable: "सुरू करा", disable: "बंद करा", selectLanguage: "तुमची भाषा निवडा", searchLanguage: "भाषा शोधा", confirmSelection: "निवड पूर्ण करा" },
  ta: { next: "அடுத்து", skip: "தவிர்", back: "பின்", prev: "முந்தையது", done: "முடிந்தது", add: "சேர்", generate: "சமையல் குறிப்பு உருவாக்கு", generating: "செய்முறை உருவாகிறது…", suggestions: "பரிந்துரைகள்", recipes: "உங்கள் செய்முறைகள்", ingredients: "பொருட்கள்", steps: "படிகள்", minutes: "நிமிடம்", preferences: "விருப்பங்கள்", share: "பகிர்", download: "பதிவிறக்கு", saved: "சேமிக்கப்பட்டது", send: "அனுப்பு", enable: "இயக்கு", disable: "நிறுத்து", selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்", searchLanguage: "மொழியைத் தேடு", confirmSelection: "தேர்வை உறுதிசெய்" },
  te: { next: "తదుపరి", skip: "దాటవేయి", back: "వెనుకకు", prev: "మునుపటి", done: "పూర్తయింది", add: "జోడించు", generate: "వంటకాలు సృష్టించు", generating: "వంటకాలు సిద్ధమవుతున్నాయి…", suggestions: "సూచనలు", recipes: "మీ వంటకాలు", ingredients: "పదార్థాలు", steps: "విధానం", minutes: "నిమిషాలు", preferences: "ప్రాధాన్యతలు", share: "పంచుకో", download: "డౌన్‌లోడ్", saved: "సేవ్ అయింది", send: "పంపు", enable: "ఆన్ చేయి", disable: "ఆఫ్ చేయి", selectLanguage: "మీ భాషను ఎంచుకోండి", searchLanguage: "భాషను వెతకండి", confirmSelection: "ఎంపిక పూర్తి" },
  kn: { next: "ಮುಂದೆ", skip: "ಬಿಟ್ಟುಬಿಡಿ", back: "ಹಿಂದೆ", prev: "ಹಿಂದಿನದು", done: "ಮುಗಿದಿದೆ", add: "ಸೇರಿಸಿ", generate: "ಪಾಕವಿಧಾನ ರಚಿಸಿ", generating: "ಪಾಕವಿಧಾನ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…", suggestions: "ಸಲಹೆಗಳು", recipes: "ನಿಮ್ಮ ಪಾಕವಿಧಾನಗಳು", ingredients: "ಪದಾರ್ಥಗಳು", steps: "ಹಂತಗಳು", minutes: "ನಿಮಿಷ", preferences: "ಆದ್ಯತೆಗಳು", share: "ಹಂಚಿಕೊಳ್ಳಿ", download: "ಡೌನ್‌ಲೋಡ್", saved: "ಉಳಿಸಲಾಗಿದೆ", send: "ಕಳುಹಿಸಿ", enable: "ಆನ್ ಮಾಡಿ", disable: "ಆಫ್ ಮಾಡಿ", selectLanguage: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ", searchLanguage: "ಭಾಷೆ ಹುಡುಕಿ", confirmSelection: "ಆಯ್ಕೆ ಖಚಿತಪಡಿಸಿ" },
  ml: { next: "അടുത്തത്", skip: "ഒഴിവാക്കുക", back: "തിരികെ", prev: "മുൻപത്തേത്", done: "പൂർത്തിയായി", add: "ചേർക്കുക", generate: "പാചകക്കുറിപ്പ് ഉണ്ടാക്കുക", generating: "പാചകക്കുറിപ്പ് തയ്യാറാകുന്നു…", suggestions: "നിർദ്ദേശങ്ങൾ", recipes: "നിങ്ങളുടെ പാചകക്കുറിപ്പുകൾ", ingredients: "ചേരുവകൾ", steps: "ഘട്ടങ്ങൾ", minutes: "മിനിറ്റ്", preferences: "മുൻഗണനകൾ", share: "പങ്കിടുക", download: "ഡൗൺലോഡ്", saved: "സേവ് ചെയ്തു", send: "അയയ്ക്കുക", enable: "ഓണാക്കുക", disable: "ഓഫാക്കുക", selectLanguage: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക", searchLanguage: "ഭാഷ തിരയുക", confirmSelection: "തിരഞ്ഞെടുപ്പ് സ്ഥിരീകരിക്കുക" },
  or: { next: "ପରବର୍ତ୍ତୀ", skip: "ଛାଡ଼ନ୍ତୁ", back: "ପଛକୁ", prev: "ପୂର୍ବବର୍ତ୍ତୀ", done: "ସମାପ୍ତ", add: "ଯୋଡ଼ନ୍ତୁ", generate: "ରେସିପି ତିଆରି କରନ୍ତୁ", generating: "ରେସିପି ପ୍ରସ୍ତୁତ ହେଉଛି…", suggestions: "ପରାମର୍ଶ", recipes: "ଆପଣଙ୍କ ରେସିପି", ingredients: "ଉପାଦାନ", steps: "ପ୍ରସ୍ତୁତି", minutes: "ମିନିଟ୍", preferences: "ପସନ୍ଦ", share: "ସେୟାର୍", download: "ଡାଉନଲୋଡ୍", saved: "ସଞ୍ଚିତ", send: "ପଠାନ୍ତୁ", enable: "ଚାଲୁ କରନ୍ତୁ", disable: "ବନ୍ଦ କରନ୍ତୁ", selectLanguage: "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ", searchLanguage: "ଭାଷା ଖୋଜନ୍ତୁ", confirmSelection: "ଚୟନ ନିଶ୍ଚିତ କରନ୍ତୁ" },
  as: { next: "পৰৱৰ্তী", skip: "এৰি যাওক", back: "পিছলৈ", prev: "পূৰ্বৰ", done: "সম্পন্ন", add: "যোগ কৰক", generate: "ৰেচিপি বনাওক", generating: "ৰেচিপি প্ৰস্তুত হৈ আছে…", suggestions: "পৰামৰ্শ", recipes: "আপোনাৰ ৰেচিপি", ingredients: "উপাদান", steps: "প্ৰস্তুত প্ৰণালী", minutes: "মিনিট", preferences: "পছন্দ", share: "শ্বেয়াৰ", download: "ডাউনল'ড", saved: "সংৰক্ষিত", send: "পঠিয়াওক", enable: "চালু কৰক", disable: "বন্ধ কৰক", selectLanguage: "আপোনাৰ ভাষা বাছনি কৰক", searchLanguage: "ভাষা বিচাৰক", confirmSelection: "বাছনি সম্পূৰ্ণ কৰক" },
  my: { next: "ရှေ့သို့", skip: "ကျော်ရန်", back: "နောက်သို့", prev: "ယခင်", done: "ပြီးပါပြီ", add: "ထည့်ရန်", generate: "ချက်နည်း ဖန်တီးရန်", generating: "ချက်နည်း ပြင်ဆင်နေသည်…", suggestions: "အကြံပြုချက်", recipes: "သင့်ချက်နည်းများ", ingredients: "ပါဝင်ပစ္စည်း", steps: "အဆင့်များ", minutes: "မိနစ်", preferences: "ဦးစားပေးများ", share: "မျှဝေရန်", download: "ဒေါင်းလုဒ်", saved: "သိမ်းပြီး", send: "ပို့ရန်", enable: "ဖွင့်ရန်", disable: "ပိတ်ရန်", selectLanguage: "သင့်ဘာသာစကား ရွေးပါ", searchLanguage: "ဘာသာစကား ရှာရန်", confirmSelection: "ရွေးချယ်မှု အတည်ပြုရန်" },
  km: { next: "បន្ទាប់", skip: "រំលង", back: "ត្រឡប់", prev: "មុន", done: "រួចរាល់", add: "បន្ថែម", generate: "បង្កើតរូបមន្ត", generating: "កំពុងបង្កើតរូបមន្ត…", suggestions: "សំណើ", recipes: "រូបមន្តរបស់អ្នក", ingredients: "គ្រឿងផ្សំ", steps: "ជំហាន", minutes: "នាទី", preferences: "ចំណូលចិត្ត", share: "ចែករំលែក", download: "ទាញយក", saved: "បានរក្សាទុក", send: "ផ្ញើ", enable: "បើក", disable: "បិទ", selectLanguage: "ជ្រើសរើសភាសារបស់អ្នក", searchLanguage: "ស្វែងរកភាសា", confirmSelection: "បញ្ជាក់ការជ្រើសរើស" },
  lo: { next: "ຕໍ່ໄປ", skip: "ຂ້າມ", back: "ກັບຄືນ", prev: "ກ່ອນໜ້າ", done: "ສຳເລັດ", add: "ເພີ່ມ", generate: "ສ້າງສູດອາຫານ", generating: "ກຳລັງສ້າງສູດ…", suggestions: "ຄຳແນະນຳ", recipes: "ສູດຂອງທ່ານ", ingredients: "ສ່ວນປະກອບ", steps: "ຂັ້ນຕອນ", minutes: "ນາທີ", preferences: "ການຕັ້ງຄ່າ", share: "ແບ່ງປັນ", download: "ດາວໂຫຼດ", saved: "ບັນທຶກແລ້ວ", send: "ສົ່ງ", enable: "ເປີດ", disable: "ປິດ", selectLanguage: "ເລືອກພາສາຂອງທ່ານ", searchLanguage: "ຄົ້ນຫາພາສາ", confirmSelection: "ຢືນຢັນການເລືອກ" },
  am: { next: "ቀጣይ", skip: "ዝለል", back: "ተመለስ", prev: "ቀዳሚ", done: "ተጠናቀቀ", add: "አክል", generate: "የምግብ አዘገጃጀት ፍጠር", generating: "አዘገጃጀት እየተዘጋጀ ነው…", suggestions: "ጥቆማዎች", recipes: "የእርስዎ የምግብ አዘገጃጀቶች", ingredients: "ግብዓቶች", steps: "ደረጃዎች", minutes: "ደቂቃ", preferences: "ምርጫዎች", share: "አጋራ", download: "አውርድ", saved: "ተቀምጧል", send: "ላክ", enable: "አብራ", disable: "አጥፋ", selectLanguage: "ቋንቋዎን ይምረጡ", searchLanguage: "ቋንቋ ፈልግ", confirmSelection: "ምርጫን አረጋግጥ" },
  sw: { next: "Endelea", skip: "Ruka", back: "Rudi", prev: "Nyuma", done: "Imekamilika", add: "Ongeza", generate: "Tengeneza mapishi", generating: "Inatengeneza mapishi…", suggestions: "Mapendekezo", recipes: "Mapishi yako", ingredients: "Viungo", steps: "Hatua", minutes: "dakika", preferences: "Mapendeleo", share: "Shiriki", download: "Pakua", saved: "Imehifadhiwa", send: "Tuma", enable: "Washa", disable: "Zima", selectLanguage: "Chagua lugha yako", searchLanguage: "Tafuta lugha", confirmSelection: "Thibitisha chaguo" },
  yo: { next: "Tẹ̀síwájú", skip: "Fò ó", back: "Padà", prev: "Ti ṣáájú", done: "Tán", add: "Fikun", generate: "Ṣẹ̀dá ìlànà oúnjẹ", generating: "Ń ṣẹ̀dá ìlànà oúnjẹ…", suggestions: "Àbá", recipes: "Àwọn ìlànà oúnjẹ rẹ", ingredients: "Àwọn ohun èlò", steps: "Àwọn ìgbésẹ̀", minutes: "ìṣẹ́jú", preferences: "Àwọn ìfẹ́", share: "Pín", download: "Gbà sílẹ̀", saved: "Ti fipamọ́", send: "Fi ránṣẹ́", enable: "Tan", disable: "Pa", selectLanguage: "Yan èdè rẹ", searchLanguage: "Wá èdè", confirmSelection: "Jẹ́rìí sí àṣàyàn" },
  ha: { next: "Gaba", skip: "Tsallake", back: "Koma", prev: "Baya", done: "An gama", add: "Ƙara", generate: "Ƙirƙiri girke-girke", generating: "Ana ƙirƙirar girke-girke…", suggestions: "Shawarwari", recipes: "Girke-girkenka", ingredients: "Kayan haɗi", steps: "Matakai", minutes: "minti", preferences: "Zaɓuɓɓuka", share: "Raba", download: "Sauke", saved: "An ajiye", send: "Aika", enable: "Kunna", disable: "Kashe", selectLanguage: "Zaɓi harshenka", searchLanguage: "Nemi harshe", confirmSelection: "Tabbatar da zaɓi" },
};
