// Regional & iconic Bangladeshi dishes.
//
// Every name here is a real dish name people actually use in Bangladesh.
// No invented "X দিয়ে Y [method]" combinations are produced here — only
// established dish names (including genuine ones like "সরিষা দিয়ে মাছ").


import { lookupIngredient } from "./pantry-data";
import type { DbRecipe, Difficulty, SpiceLevel } from "./recipe-db-types";

const bn = (en: string) => lookupIngredient(en)?.bn ?? en;

type MethodSpec = {
  cookTime: number;
  difficulty: Difficulty;
  spiceLevel: SpiceLevel;
  tags: string[];
  staples: string[];
  stepsBn: (n: string) => string[];
  stepsEn: (n: string) => string[];
};

const M = {
  bharta: {
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: 3,
    tags: ["ভর্তা", "side"],
    staples: ["Onion", "Green chilli", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} সেদ্ধ বা পুড়িয়ে নরম করে নিন।`,
      "পেঁয়াজ ও কাঁচা মরিচ কুচি করুন।",
      "সব একসাথে লবণ দিয়ে চটকে মাখুন।",
      "তেল দিয়ে মেখে ভাতের সাথে দিন।",
    ],
    stepsEn: (n: string) => [
      `Soften the ${n} by boiling or charring.`,
      "Chop onion and green chilli.",
      "Mash everything together with salt.",
      "Finish with mustard oil and serve with rice.",
    ],
  },
  bhaji: {
    cookTime: 18,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["ভাজি", "side"],
    staples: ["Onion", "Turmeric", "Green chilli", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} ধুয়ে পাতলা করে কেটে নিন।`,
      "কড়াইয়ে তেল গরম করে পেঁয়াজ ভাজুন।",
      "হলুদ, মরিচ ও লবণ দিয়ে নাড়ুন।",
      `${n} দিয়ে ঢেকে নরম হওয়া পর্যন্ত ভাজুন।`,
    ],
    stepsEn: (n: string) => [
      `Wash and slice the ${n} thin.`,
      "Heat oil and fry the onion.",
      "Add turmeric, chilli and salt.",
      `Add the ${n}, cover and fry until tender.`,
    ],
  },
  bhuna: {
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: 4,
    tags: ["ভুনা", "main"],
    staples: ["Onion", "Garlic", "Ginger", "Turmeric", "Red chilli powder", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      "তেলে পেঁয়াজ কুচি বাদামি করে ভাজুন।",
      "আদা-রসুন বাটা ও গুঁড়া মসলা কষান।",
      `${n} দিয়ে ভালো করে কষিয়ে নিন।`,
      "অল্প পানি দিয়ে ঢেকে রান্না করুন।",
      "তেল উপরে উঠে এলে নামিয়ে নিন।",
    ],
    stepsEn: (n: string) => [
      "Brown the sliced onion in oil.",
      "Fry ginger-garlic paste and ground spices.",
      `Add the ${n} and fry into the masala.`,
      "Add a little water, cover and cook.",
      "Cook until the oil separates, then serve.",
    ],
  },
  jhol: {
    cookTime: 25,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["ঝোল", "main"],
    staples: ["Onion", "Turmeric", "Cumin", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      "তেলে পেঁয়াজ ও মসলা কষিয়ে নিন।",
      `${n} দিয়ে হালকা নেড়ে নিন।`,
      "পরিমাণমতো পানি দিয়ে ফুটতে দিন।",
      "ঝোল মাখা মাখা হলে নামিয়ে নিন।",
    ],
    stepsEn: (n: string) => [
      "Fry onion and spices in oil.",
      `Stir in the ${n} briefly.`,
      "Pour in water and bring to a boil.",
      "Simmer until the gravy thickens slightly.",
    ],
  },
  curry: {
    cookTime: 35,
    difficulty: "medium",
    spiceLevel: 3,
    tags: ["কারি", "main"],
    staples: ["Onion", "Garlic", "Ginger", "Turmeric", "Garam masala", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      "পেঁয়াজ, আদা ও রসুন বাটা তেলে কষান।",
      "হলুদ, মরিচ ও লবণ দিয়ে মসলা ভাজুন।",
      `${n} দিয়ে দশ মিনিট কষিয়ে নিন।`,
      "গরম পানি দিয়ে ঢেকে সেদ্ধ করুন।",
      "গরম মসলা ছিটিয়ে নামিয়ে নিন।",
    ],
    stepsEn: (n: string) => [
      "Fry onion, ginger and garlic paste in oil.",
      "Add turmeric, chilli and salt to the masala.",
      `Add the ${n} and fry for ten minutes.`,
      "Pour hot water, cover and cook through.",
      "Finish with garam masala and serve.",
    ],
  },
  dopeyaja: {
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: 3,
    tags: ["দোপেঁয়াজা", "main"],
    staples: ["Onion", "Garlic", "Turmeric", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      "অর্ধেক পেঁয়াজ কুচি ভেজে বাদামি করুন।",
      "গুঁড়া মসলা কষিয়ে নিন।",
      `${n} দিয়ে কষিয়ে অল্প পানি দিন।`,
      "শেষে বাকি পেঁয়াজ ফালি দিয়ে দমে রাখুন।",
    ],
    stepsEn: (n: string) => [
      "Brown half the sliced onion in oil.",
      "Fry the spice base.",
      `Add the ${n} and a splash of water.`,
      "Fold in the remaining onion slices and steam.",
    ],
  },
  torkari: {
    cookTime: 25,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["তরকারি", "main", "vegetarian"],
    staples: ["Onion", "Turmeric", "Cumin", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} ডুমো করে কেটে নিন।`,
      "তেলে পেঁয়াজ ও ফোড়ন দিন।",
      "হলুদ, জিরা ও লবণ দিয়ে কষান।",
      "সবজি ও অল্প পানি দিয়ে সেদ্ধ করুন।",
    ],
    stepsEn: (n: string) => [
      `Cut the ${n} into chunks.`,
      "Temper onion and spices in oil.",
      "Add turmeric, cumin and salt.",
      "Add the vegetables with water and cook until soft.",
    ],
  },
  dal: {
    cookTime: 25,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["ডাল", "vegetarian"],
    staples: ["Onion", "Garlic", "Turmeric", "Green chilli", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} ধুয়ে হলুদ-লবণ দিয়ে সেদ্ধ করুন।`,
      "ঘুঁটে মসৃণ করে নিন।",
      "তেলে পেঁয়াজ, রসুন ও মরিচ ফোড়ন দিন।",
      "ফোড়ন ডালে ঢেলে ফুটিয়ে নামান।",
    ],
    stepsEn: (n: string) => [
      `Boil the ${n} with turmeric and salt.`,
      "Whisk until smooth.",
      "Temper onion, garlic and chilli in oil.",
      "Pour the tempering into the dal and simmer.",
    ],
  },
  khichuri: {
    cookTime: 40,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["খিচুড়ি", "one-pot"],
    staples: ["Onion", "Ginger", "Turmeric", "Bay leaf", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      "চাল ও ডাল ধুয়ে নিন।",
      "তেলে পেঁয়াজ, তেজপাতা ও আদা ফোড়ন দিন।",
      `${n} দিয়ে হলুদ-লবণসহ ভাজুন।`,
      "গরম পানি দিয়ে ঢেকে সেদ্ধ করুন।",
      "মাখা মাখা হলে ঘি দিয়ে নামান।",
    ],
    stepsEn: (n: string) => [
      "Rinse the rice and lentils.",
      "Temper onion, bay leaf and ginger in oil.",
      `Fry the ${n} with turmeric and salt.`,
      "Add hot water, cover and cook.",
      "Finish with ghee when thick.",
    ],
  },
  polao: {
    cookTime: 40,
    difficulty: "medium",
    spiceLevel: 1,
    tags: ["পোলাও", "festive"],
    staples: ["Onion", "Ginger", "Cardamom", "Cinnamon", "Bay leaf", "Ghee", "Salt"],
    stepsBn: (n: string) => [
      "চাল ধুয়ে পানি ঝরিয়ে নিন।",
      "ঘিয়ে গরম মসলা ও পেঁয়াজ ভাজুন।",
      `${n} দিয়ে কয়েক মিনিট ভাজুন।`,
      "মেপে গরম পানি দিয়ে ঢেকে দিন।",
      "পানি শুকালে দমে দশ মিনিট রাখুন।",
    ],
    stepsEn: (n: string) => [
      "Wash and drain the rice.",
      "Fry whole spices and onion in ghee.",
      `Add the ${n} and fry a few minutes.`,
      "Add measured hot water and cover.",
      "Rest on low heat for ten minutes.",
    ],
  },
  biryani: {
    cookTime: 75,
    difficulty: "hard",
    spiceLevel: 3,
    tags: ["বিরিয়ানি", "festive", "main"],
    staples: ["Onion", "Ginger", "Garlic", "Yogurt", "Garam masala", "Ghee", "Salt"],
    stepsBn: (n: string) => [
      `${n} দই ও মসলায় মেখে রাখুন।`,
      "পেঁয়াজ বেরেস্তা ভেজে তুলুন।",
      "মাংস কষিয়ে আধা সেদ্ধ করুন।",
      "আধা সেদ্ধ চাল স্তরে স্তরে সাজান।",
      "ঢাকনা এঁটে অল্প আঁচে দমে রাখুন।",
    ],
    stepsEn: (n: string) => [
      `Marinate the ${n} in yogurt and spices.`,
      "Fry crisp onion beresta and set aside.",
      "Cook the meat until half done.",
      "Layer with parboiled rice.",
      "Seal and cook on dum over low heat.",
    ],
  },
  bora: {
    cookTime: 20,
    difficulty: "easy",
    spiceLevel: 3,
    tags: ["বড়া", "snack", "fried"],
    staples: ["Onion", "Green chilli", "Gram flour", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} কুচি বা বেটে নিন।`,
      "বেসন, পেঁয়াজ, মরিচ ও লবণ মেশান।",
      "অল্প পানি দিয়ে ঘন মিশ্রণ বানান।",
      "গরম তেলে ছোট ছোট বড়া ভেজে তুলুন।",
    ],
    stepsEn: (n: string) => [
      `Chop or grind the ${n}.`,
      "Mix with gram flour, onion, chilli and salt.",
      "Add a little water for a thick batter.",
      "Fry small fritters until golden.",
    ],
  },
  fry: {
    cookTime: 15,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["ভাজা", "fried", "side"],
    staples: ["Turmeric", "Red chilli powder", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} ধুয়ে পানি ঝরিয়ে নিন।`,
      "হলুদ, মরিচ ও লবণ মেখে রাখুন।",
      "কড়াইয়ে তেল গরম করুন।",
      "দুই পিঠ সোনালি করে ভেজে তুলুন।",
    ],
    stepsEn: (n: string) => [
      `Rinse and drain the ${n}.`,
      "Rub with turmeric, chilli and salt.",
      "Heat oil in a pan.",
      "Fry golden on both sides.",
    ],
  },
  shutki: {
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: 5,
    tags: ["শুঁটকি", "main"],
    staples: ["Onion", "Garlic", "Turmeric", "Red chilli powder", "Mustard oil", "Salt"],
    stepsBn: (n: string) => [
      "শুঁটকি গরম পানিতে ভিজিয়ে ভালো করে ধুয়ে নিন।",
      "তেলে পেঁয়াজ ও রসুন ভাজুন।",
      "গুঁড়া মসলা কষিয়ে নিন।",
      `${n} দিয়ে কষিয়ে অল্প পানি দিন।`,
      "মাখা মাখা হলে নামিয়ে নিন।",
    ],
    stepsEn: (n: string) => [
      "Soak the dried fish in hot water and rinse well.",
      "Fry onion and garlic in oil.",
      "Cook the ground spices into a masala.",
      `Add the ${n} with a splash of water.`,
      "Cook down until thick and serve.",
    ],
  },
  tenga: {
    cookTime: 25,
    difficulty: "easy",
    spiceLevel: 2,
    tags: ["টক", "main"],
    staples: ["Onion", "Turmeric", "Nigella seed", "Tamarind", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      "তেলে কালোজিরা ও পেঁয়াজ ফোড়ন দিন।",
      "হলুদ ও লবণ দিয়ে কষান।",
      `${n} ও পানি দিয়ে ফুটিয়ে নিন।`,
      "তেঁতুলের ক্বাথ দিয়ে টক ঝোল বানিয়ে নামান।",
    ],
    stepsEn: (n: string) => [
      "Temper nigella seed and onion in oil.",
      "Add turmeric and salt.",
      `Add the ${n} with water and simmer.`,
      "Stir in tamarind pulp for a sour gravy.",
    ],
  },
  malaikari: {
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: 2,
    tags: ["মালাইকারি", "festive", "main"],
    staples: ["Onion", "Ginger", "Turmeric", "Cardamom", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} হলুদ-লবণ মেখে হালকা ভেজে তুলুন।`,
      "তেলে এলাচ ও পেঁয়াজ বাটা কষান।",
      "নারকেলের দুধ ঢেলে ফুটতে দিন।",
      "ভাজা উপকরণ দিয়ে পাঁচ মিনিট রেখে নামান।",
    ],
    stepsEn: (n: string) => [
      `Toss the ${n} in turmeric and salt and fry lightly.`,
      "Fry cardamom and onion paste in oil.",
      "Pour in coconut milk and simmer.",
      "Return the fried pieces for five minutes.",
    ],
  },
  patuari: {
    cookTime: 35,
    difficulty: "medium",
    spiceLevel: 3,
    tags: ["পাতুরি", "steamed", "main"],
    staples: ["Mustard seed", "Green chilli", "Turmeric", "Mustard oil", "Salt"],
    stepsBn: (n: string) => [
      "সরিষা ও কাঁচা মরিচ বেটে নিন।",
      `${n} সরিষা বাটা, হলুদ ও লবণ দিয়ে মাখুন।`,
      "কলাপাতায় মুড়ে সুতো দিয়ে বেঁধে নিন।",
      "তাওয়ায় বা ভাপে পনেরো মিনিট রান্না করুন।",
    ],
    stepsEn: (n: string) => [
      "Grind mustard seed with green chilli.",
      `Coat the ${n} in the paste with turmeric and salt.`,
      "Wrap in banana leaf and tie.",
      "Steam or pan-cook for fifteen minutes.",
    ],
  },
  kalabhuna: {
    cookTime: 90,
    difficulty: "hard",
    spiceLevel: 5,
    tags: ["কালা ভুনা", "main"],
    staples: ["Onion", "Garlic", "Ginger", "Garam masala", "Red chilli powder", "Mustard oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} আদা-রসুন ও গুঁড়া মসলায় মেখে রাখুন।`,
      "ঢেকে নিজের পানিতে সেদ্ধ করুন।",
      "পানি শুকিয়ে গেলে তেল দিয়ে দীর্ঘক্ষণ কষান।",
      "মাংস কালচে বাদামি হওয়া পর্যন্ত নাড়ুন।",
      "ভাজা পেঁয়াজ ও গরম মসলা দিয়ে নামান।",
    ],
    stepsEn: (n: string) => [
      `Marinate the ${n} with ginger-garlic and ground spices.`,
      "Cook covered in its own liquid.",
      "Once dry, add oil and fry long and slow.",
      "Keep stirring until deep brown-black.",
      "Finish with fried onion and garam masala.",
    ],
  },
  kabab: {
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: 3,
    tags: ["কাবাব", "snack", "fried"],
    staples: ["Onion", "Ginger", "Garlic", "Garam masala", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} মিহি করে বেটে বা কিমা করে নিন।`,
      "পেঁয়াজ, আদা-রসুন ও মসলা মেশান।",
      "হাতে চ্যাপ্টা কাবাব গড়ুন।",
      "অল্প তেলে দুই পিঠ ভেজে তুলুন।",
    ],
    stepsEn: (n: string) => [
      `Mince or grind the ${n} fine.`,
      "Mix with onion, ginger-garlic and spices.",
      "Shape into flat patties.",
      "Shallow-fry until browned on both sides.",
    ],
  },
  chop: {
    cookTime: 30,
    difficulty: "medium",
    spiceLevel: 3,
    tags: ["চপ", "snack", "fried"],
    staples: ["Onion", "Green chilli", "Garam masala", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} সেদ্ধ করে চটকে পুর বানান।`,
      "পেঁয়াজ, মরিচ ও মসলা মিশিয়ে নিন।",
      "গোল বা লম্বা আকার দিন।",
      "বিস্কুটের গুঁড়ায় গড়িয়ে ডুবো তেলে ভাজুন।",
    ],
    stepsEn: (n: string) => [
      `Boil and mash the ${n} for the filling.`,
      "Mix in onion, chilli and spices.",
      "Shape into rounds or cylinders.",
      "Coat in crumbs and deep-fry.",
    ],
  },
  bread: {
    cookTime: 25,
    difficulty: "medium",
    spiceLevel: 0,
    tags: ["রুটি", "breakfast"],
    staples: ["Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} দিয়ে নরম খামির মেখে নিন।`,
      "ঢেকে পনেরো মিনিট রাখুন।",
      "লেচি কেটে পাতলা করে বেলুন।",
      "গরম তাওয়ায় দুই পিঠ সেঁকে নিন।",
    ],
    stepsEn: (n: string) => [
      `Knead a soft dough with the ${n}.`,
      "Rest it covered for fifteen minutes.",
      "Divide and roll out thin.",
      "Cook on a hot tawa on both sides.",
    ],
  },
  sweet: {
    cookTime: 40,
    difficulty: "medium",
    spiceLevel: 0,
    tags: ["মিষ্টি", "dessert", "sweet"],
    staples: ["Sugar", "Cardamom", "Ghee"],
    stepsBn: (n: string) => [
      "দুধ জ্বাল দিয়ে ঘন করুন।",
      `${n} দিয়ে অল্প আঁচে নাড়ুন।`,
      "চিনি ও এলাচ দিয়ে মিষ্টি করুন।",
      "ঘন হলে নামিয়ে ঠান্ডা করে পরিবেশন করুন।",
    ],
    stepsEn: (n: string) => [
      "Reduce the milk until thick.",
      `Stir in the ${n} on low heat.`,
      "Sweeten with sugar and cardamom.",
      "Cool slightly and serve.",
    ],
  },
  snack: {
    cookTime: 20,
    difficulty: "easy",
    spiceLevel: 3,
    tags: ["নাস্তা", "snack"],
    staples: ["Onion", "Green chilli", "Cooking oil", "Salt"],
    stepsBn: (n: string) => [
      `${n} প্রস্তুত করে নিন।`,
      "পেঁয়াজ, মরিচ ও মসলা মেশান।",
      "স্বাদমতো লবণ ও টক দিন।",
      "মেখে গরম গরম পরিবেশন করুন।",
    ],
    stepsEn: (n: string) => [
      `Prepare the ${n}.`,
      "Mix with onion, chilli and spices.",
      "Season with salt and something sour.",
      "Toss together and serve fresh.",
    ],
  },
} satisfies Record<string, MethodSpec>;

type MethodKey = keyof typeof M;

/** [id, bengali name, english name, method, ingredients, region, popularity] */
type CuratedRow = [string, string, string, MethodKey, string[], string, number];

const CURATED: CuratedRow[] = [
  // --- National / iconic ---------------------------------------------------
  ["nat-shorshe-ilish", "শর্ষে ইলিশ", "Shorshe Ilish", "patuari", ["Hilsa", "Mustard seed"], "national", 96],
  ["nat-ilish-paturi", "ইলিশ পাতুরি", "Ilish Paturi", "patuari", ["Hilsa", "Mustard seed"], "national", 88],
  ["nat-panta-bhat", "পান্তা ভাত", "Panta Bhat", "snack", ["Cooked rice", "Onion", "Green chilli"], "national", 90],
  ["nat-bhuna-khichuri", "ভুনা খিচুড়ি", "Bhuna Khichuri", "khichuri", ["Rice", "Mung dal"], "national", 95],
  ["nat-murgi-biryani", "মুরগির বিরিয়ানি", "Chicken Biryani", "biryani", ["Chicken", "Rice", "Yogurt"], "national", 94],
  ["nat-gorur-biryani", "গরুর বিরিয়ানি", "Beef Biryani", "biryani", ["Beef", "Rice", "Yogurt"], "national", 88],
  ["nat-khashir-biryani", "খাসির বিরিয়ানি", "Mutton Biryani", "biryani", ["Mutton", "Rice", "Yogurt"], "national", 90],
  ["nat-semai", "সেমাই", "Shemai", "sweet", ["Milk", "Semolina", "Raisin"], "national", 92],
  ["nat-semai-payesh", "সেমাই পায়েস", "Shemai Payesh", "sweet", ["Milk", "Semolina", "Cashew"], "national", 85],
  ["nat-mishti-doi", "মিষ্টি দই", "Mishti Doi", "sweet", ["Yogurt", "Milk", "Jaggery"], "national", 89],
  ["nat-rosogolla", "রসগোল্লা", "Rosogolla", "sweet", ["Cottage cheese", "Milk"], "national", 87],
  ["nat-chanar-jilapi", "ছানার জিলাপি", "Chanar Jilapi", "sweet", ["Cottage cheese", "Maida"], "national", 72],
  ["nat-chanar-dalna", "ছানার ডালনা", "Chanar Dalna", "curry", ["Cottage cheese", "Potato"], "national", 70],
  ["nat-payesh", "চালের পায়েস", "Payesh", "sweet", ["Rice", "Milk", "Raisin"], "national", 91],
  ["nat-kumra-payesh", "কুমড়ার পায়েস", "Pumpkin Payesh", "sweet", ["Pumpkin", "Milk"], "national", 62],
  ["nat-balish-mishti", "বালিশ মিষ্টি", "Balish Mishti", "sweet", ["Cottage cheese", "Milk"], "netrokona", 55],

  // --- Fish -----------------------------------------------------------------
  ["fish-macher-jhol", "মাছের ঝোল", "Macher Jhol", "jhol", ["Rui fish", "Potato"], "national", 95],
  ["fish-macher-curry", "মাছের কারি", "Fish Curry", "curry", ["Katla fish", "Onion"], "national", 90],
  ["fish-patla-jhol", "পাতলা মাছের ঝোল", "Patla Macher Jhol", "jhol", ["Tilapia", "Potato"], "national", 84],
  ["fish-rui-bhuna", "রুই মাছ ভুনা", "Rui Bhuna", "bhuna", ["Rui fish", "Onion"], "national", 86],
  ["fish-katla-curry", "কাতলা মাছের কারি", "Katla Curry", "curry", ["Katla fish", "Onion"], "national", 80],
  ["fish-ilish-bhaji", "ইলিশ ভাজি", "Ilish Bhaji", "fry", ["Hilsa"], "national", 90],
  ["fish-ilish-jhol", "ইলিশ মাছের ঝোল", "Ilish Jhol", "jhol", ["Hilsa", "Eggplant"], "national", 85],
  ["fish-rupchanda-bhaja", "রুপচাঁদা ভাজা", "Rupchanda Bhaja", "fry", ["Tilapia"], "chittagong", 78],
  ["fish-pangas-curry", "পাঙ্গাশ মাছের কারি", "Pangas Curry", "curry", ["Pangas", "Potato"], "national", 82],
  ["fish-pangas-bhuna", "পাঙ্গাশ ভুনা", "Pangas Bhuna", "bhuna", ["Pangas", "Onion"], "national", 74],
  ["fish-tilapia-bhuna", "তেলাপিয়া ভুনা", "Tilapia Bhuna", "bhuna", ["Tilapia", "Onion"], "national", 80],
  ["fish-tilapia-jhal", "তেলাপিয়া মাছের ঝাল", "Tilapia Jhal", "bhuna", ["Tilapia", "Green chilli"], "national", 72],
  ["fish-koi-bhaji", "কই মাছ ভাজি", "Koi Bhaji", "fry", ["Rui fish"], "national", 70],
  ["fish-macher-tenga", "মাছের টেঙ্গা", "Macher Tenga", "tenga", ["Rui fish", "Tomato"], "sylhet", 68],
  ["fish-tetul-macher-jhol", "তেঁতুল দিয়ে মাছের ঝোল", "Tamarind Fish Jhol", "tenga", ["Tilapia", "Tomato"], "sylhet", 60],
  ["fish-macher-malaikari", "মাছের মালাইকারি", "Fish Malaikari", "malaikari", ["Rui fish", "Coconut milk"], "national", 70],
  ["fish-chingri-malaikari", "চিংড়ি মালাই কারি", "Chingri Malai Curry", "malaikari", ["Prawn", "Coconut milk"], "khulna", 88],
  ["fish-lau-chingri", "লাউ চিংড়ি", "Lau Chingri", "torkari", ["Bottle gourd", "Prawn"], "national", 82],
  ["fish-chingri-bhuna", "চিংড়ি ভুনা", "Chingri Bhuna", "bhuna", ["Prawn", "Onion"], "national", 85],
  ["fish-mula-chingri", "মুলা দিয়ে চিংড়ি", "Radish with Prawn", "torkari", ["Radish", "Prawn"], "national", 62],
  ["fish-shutki-bharta", "শুঁটকি ভর্তা", "Shutki Bharta", "bharta", ["Dried fish"], "chittagong", 84],
  ["fish-shutki-bhuna", "শুঁটকি ভুনা", "Shutki Bhuna", "shutki", ["Dried fish", "Onion"], "chittagong", 82],
  ["fish-shutki-alu", "আলু দিয়ে শুঁটকি", "Shutki with Potato", "shutki", ["Dried fish", "Potato"], "chittagong", 70],
  ["fish-shutki-begun", "বেগুন দিয়ে শুঁটকি", "Shutki with Eggplant", "shutki", ["Dried fish", "Eggplant"], "chittagong", 66],
  ["fish-shutki-dim", "শুঁটকি দিয়ে ডিম", "Shutki with Egg", "shutki", ["Dried fish", "Egg"], "sylhet", 60],
  ["fish-shutki-dopeyaja", "শুঁটকি দোপেঁয়াজা", "Shutki Dopeyaja", "dopeyaja", ["Dried fish", "Onion"], "sylhet", 58],
  ["fish-macher-dopeyaja", "মাছের দোপেঁয়াজা", "Fish Dopeyaja", "dopeyaja", ["Rui fish", "Onion"], "national", 66],
  ["fish-macher-bora", "মাছের বড়া", "Macher Bora", "bora", ["Rui fish"], "national", 58],
  ["fish-macher-kofta", "মাছের কোফতা", "Fish Kofta", "kabab", ["Rui fish", "Potato"], "national", 55],
  ["fish-tuna-bharta", "টুনা ভর্তা", "Tuna Bharta", "bharta", ["Tuna (canned)"], "national", 45],
  ["fish-sorse-macher-jhal", "সরিষা দিয়ে মাছ", "Mustard Fish", "patuari", ["Rui fish", "Mustard seed"], "national", 72],
  ["fish-begun-macher-jhol", "বেগুন দিয়ে মাছের ঝোল", "Fish Jhol with Eggplant", "jhol", ["Rui fish", "Eggplant"], "national", 76],
  ["fish-mula-macher-jhol", "মুলা দিয়ে মাছের ঝোল", "Fish Jhol with Radish", "jhol", ["Rui fish", "Radish"], "national", 64],
  ["fish-fulkopi-mach", "ফুলকপি দিয়ে মাছ", "Fish with Cauliflower", "jhol", ["Rui fish", "Cauliflower"], "national", 68],
  ["fish-palong-mach", "পালং শাক দিয়ে মাছ", "Fish with Spinach", "jhol", ["Rui fish", "Spinach"], "national", 58],
  ["fish-kumra-mach", "কুমড়া দিয়ে মাছ", "Fish with Pumpkin", "jhol", ["Rui fish", "Pumpkin"], "national", 56],
  ["fish-chingri-bharta", "চিংড়ি ভর্তা", "Chingri Bharta", "bharta", ["Prawn"], "national", 74],
  ["fish-loitta-bhuna", "লইট্টা শুঁটকি ভুনা", "Loitta Shutki Bhuna", "shutki", ["Dried fish", "Green chilli"], "chittagong", 66],

  // --- Chittagong -----------------------------------------------------------
  ["ctg-kala-bhuna", "কালা ভুনা", "Kala Bhuna", "kalabhuna", ["Beef", "Onion"], "chittagong", 92],
  ["ctg-mejbani-gosht", "মেজবানি গোশত", "Mejbani Gosht", "bhuna", ["Beef", "Onion"], "chittagong", 88],
  ["ctg-jhal-mangsho", "ঝাল মাংস", "Jhal Mangsho", "bhuna", ["Beef", "Green chilli"], "chittagong", 78],
  ["ctg-akhni", "আখনি", "Akhni", "polao", ["Rice", "Beef"], "chittagong", 76],
  ["ctg-murgi-akhni", "মুরগির আখনি", "Chicken Akhni", "polao", ["Rice", "Chicken"], "chittagong", 74],
  ["ctg-nolar-kanji", "নলার কাঞ্জি", "Nolar Kanji", "curry", ["Beef", "Rice"], "chittagong", 52],
  ["ctg-harer-jhol", "গরুর হাড়ের ঝোল", "Beef Bone Jhol", "jhol", ["Beef", "Potato"], "chittagong", 68],
  ["ctg-cholar-dal", "ছোলার ডাল", "Cholar Dal", "dal", ["Split chickpeas", "Coconut"], "chittagong", 80],
  ["ctg-mejbani-kala-bhuna", "মেজবানি কালা ভুনা", "Mejbani Kala Bhuna", "kalabhuna", ["Beef", "Garlic"], "chittagong", 70],
  ["ctg-durus-kura", "দুরুস কুরা", "Durus Kura", "curry", ["Chicken", "Onion"], "chittagong", 50],
  ["ctg-morich-gosht", "কাঁচা মরিচ দিয়ে গরুর মাংস", "Beef with Green Chilli", "bhuna", ["Beef", "Green chilli"], "chittagong", 72],
  ["ctg-mangsher-jhol", "গরুর মাংসের ঝোল", "Beef Jhol", "jhol", ["Beef", "Potato"], "chittagong", 86],

  // --- Sylhet ---------------------------------------------------------------
  ["syl-satkora-gosht", "সাতকরা দিয়ে গরুর মাংস", "Beef with Satkora", "bhuna", ["Beef", "Lemon"], "sylhet", 84],
  ["syl-hash-bhuna", "হাঁসের মাংস ভুনা", "Duck Bhuna", "bhuna", ["Duck", "Onion"], "sylhet", 86],
  ["syl-hash-narikel", "নারকেল দিয়ে হাঁসের মাংস", "Duck with Coconut", "curry", ["Duck", "Coconut milk"], "sylhet", 74],
  ["syl-hash-khichuri", "হাঁস খিচুড়ি", "Duck Khichuri", "khichuri", ["Duck", "Rice", "Mung dal"], "sylhet", 70],
  ["syl-pancher-khatta", "পাঁচ মিশালি খাট্টা", "Panch Khatta", "tenga", ["Tomato", "Potato"], "sylhet", 55],
  ["syl-chunga-pitha", "চুঙ্গা পিঠা", "Chunga Pitha", "sweet", ["Rice", "Coconut"], "sylhet", 48],
  ["syl-bansh-korol", "বাঁশ কোড়ল তরকারি", "Bamboo Shoot Torkari", "torkari", ["Green beans", "Potato"], "sylhet", 40],
  ["syl-shutki-satkora", "সাতকরা দিয়ে শুঁটকি", "Shutki with Satkora", "shutki", ["Dried fish", "Lemon"], "sylhet", 46],
  ["syl-gosht-alu", "আলু দিয়ে গরুর মাংস", "Beef with Potato", "curry", ["Beef", "Potato"], "sylhet", 88],
  ["syl-murgi-satkora", "সাতকরা দিয়ে মুরগি", "Chicken with Satkora", "bhuna", ["Chicken", "Lemon"], "sylhet", 66],

  // --- Meat -----------------------------------------------------------------
  ["meat-mangsho-bhuna", "মাংস ভুনা", "Mangsho Bhuna", "bhuna", ["Beef", "Onion"], "national", 92],
  ["meat-murgir-jhol", "মুরগির ঝোল", "Chicken Jhol", "jhol", ["Chicken", "Potato"], "national", 95],
  ["meat-murgir-curry", "মুরগির কারি", "Chicken Curry", "curry", ["Chicken", "Onion"], "national", 94],
  ["meat-murgi-bhuna", "মুরগি ভুনা", "Chicken Bhuna", "bhuna", ["Chicken", "Onion"], "national", 93],
  ["meat-murgi-roast", "মুরগির রোস্ট", "Chicken Roast", "curry", ["Chicken", "Yogurt"], "national", 85],
  ["meat-khashir-mangsho", "খাসির মাংস", "Mutton Curry", "curry", ["Mutton", "Onion"], "national", 88],
  ["meat-khashi-bhuna", "খাসির মাংস ভুনা", "Mutton Bhuna", "bhuna", ["Mutton", "Onion"], "national", 82],
  ["meat-gorur-curry", "গরুর মাংসের কারি", "Beef Curry", "curry", ["Beef", "Onion"], "national", 92],
  ["meat-gorur-rezala", "গরুর রেজালা", "Beef Rezala", "curry", ["Beef", "Yogurt"], "dhaka", 76],
  ["meat-murgir-rezala", "মুরগির রেজালা", "Chicken Rezala", "curry", ["Chicken", "Yogurt"], "dhaka", 78],
  ["meat-kofta-curry", "কোফতা কারি", "Kofta Curry", "kabab", ["Beef", "Onion"], "national", 66],
  ["meat-shami-kabab", "শামি কাবাব", "Shami Kabab", "kabab", ["Beef", "Split chickpeas"], "dhaka", 74],
  ["meat-jali-kabab", "জালি কাবাব", "Jali Kabab", "kabab", ["Beef", "Egg"], "dhaka", 68],
  ["meat-murgi-kabab", "মুরগির কাবাব", "Chicken Kabab", "kabab", ["Chicken", "Onion"], "national", 70],
  ["meat-kima-bhuna", "কিমা ভুনা", "Kima Bhuna", "bhuna", ["Beef", "Onion"], "national", 72],
  ["meat-alu-gosht", "আলু দিয়ে গোশত", "Meat with Potato", "curry", ["Beef", "Potato"], "national", 90],
  ["meat-pudina-gosht", "পুদিনা দিয়ে গোশত", "Meat with Mint", "bhuna", ["Beef", "Mint"], "national", 52],
  ["meat-mangsho-dopeyaja", "মাংস দোপেঁয়াজা", "Meat Dopeyaja", "dopeyaja", ["Beef", "Onion"], "national", 70],
  ["meat-murgi-dopeyaja", "মুরগি দোপেঁয়াজা", "Chicken Dopeyaja", "dopeyaja", ["Chicken", "Onion"], "national", 72],
  ["meat-hash-curry", "হাঁসের মাংস", "Duck Curry", "curry", ["Duck", "Potato"], "national", 68],
  ["meat-murgi-korma", "মুরগির কোরমা", "Chicken Korma", "curry", ["Chicken", "Yogurt", "Cashew"], "dhaka", 80],
  ["meat-tehari", "তেহারি", "Tehari", "biryani", ["Beef", "Rice"], "dhaka", 86],
  ["meat-morog-polao", "মোরগ পোলাও", "Morog Polao", "polao", ["Chicken", "Rice"], "dhaka", 88],
  ["meat-kacchi-biryani", "কাচ্চি বিরিয়ানি", "Kacchi Biryani", "biryani", ["Mutton", "Rice", "Yogurt"], "dhaka", 93],
  ["meat-gosht-polao", "মাংস পোলাও", "Meat Polao", "polao", ["Beef", "Rice"], "national", 74],
  ["meat-kolija-bhuna", "কলিজা ভুনা", "Kolija Bhuna", "bhuna", ["Beef", "Onion"], "national", 64],
  ["meat-korai-murgi", "কড়াই মুরগি", "Karai Chicken", "bhuna", ["Chicken", "Capsicum"], "national", 66],
  ["meat-dim-gosht", "ডিম দিয়ে মাংস", "Meat with Egg", "curry", ["Beef", "Egg"], "national", 58],

  // --- Eggs ------------------------------------------------------------------
  ["egg-dim-bhaji", "ডিম ভাজি", "Dim Bhaji", "fry", ["Egg", "Onion"], "national", 97],
  ["egg-dim-bhuna", "ডিম ভুনা", "Dim Bhuna", "bhuna", ["Egg", "Onion"], "national", 96],
  ["egg-dim-curry", "ডিম কারি", "Dim Curry", "curry", ["Egg", "Potato"], "national", 93],
  ["egg-dim-dopeyaja", "ডিম দোপেঁয়াজা", "Dim Dopeyaja", "dopeyaja", ["Egg", "Onion"], "national", 84],
  ["egg-dim-omelette", "ডিমের অমলেট", "Dimer Omelette", "fry", ["Egg", "Green chilli"], "national", 95],
  ["egg-dim-poach", "ডিম পোচ", "Dim Poach", "fry", ["Egg"], "national", 94],
  ["egg-dim-bharta", "ডিম ভর্তা", "Dim Bharta", "bharta", ["Egg"], "national", 90],
  ["egg-palong-dim", "পালং শাক দিয়ে ডিম", "Egg with Spinach", "bhaji", ["Spinach", "Egg"], "national", 72],
  ["egg-tomato-dim", "টমেটো দিয়ে ডিম কারি", "Egg Curry with Tomato", "curry", ["Egg", "Tomato"], "national", 80],
  ["egg-alu-dim", "আলু দিয়ে ডিম", "Egg with Potato", "curry", ["Egg", "Potato"], "national", 88],
  ["egg-begun-dim", "বেগুন দিয়ে ডিম", "Egg with Eggplant", "bhaji", ["Eggplant", "Egg"], "national", 62],
  ["egg-dim-khichuri", "ডিম দিয়ে ভুনা খিচুড়ি", "Bhuna Khichuri with Egg", "khichuri", ["Rice", "Mung dal", "Egg"], "national", 86],
  ["egg-dim-torkari", "ডিমের তরকারি", "Dimer Torkari", "torkari", ["Egg", "Potato"], "national", 82],
  ["egg-dim-jhol", "ডিমের ঝোল", "Dimer Jhol", "jhol", ["Egg", "Potato"], "national", 84],
  ["egg-dim-chop", "ডিম চপ", "Dim Chop", "chop", ["Egg", "Potato"], "dhaka", 76],
  ["egg-dim-polao", "ডিম পোলাও", "Dim Polao", "polao", ["Rice", "Egg"], "national", 60],
  ["egg-dim-noodles", "ডিম নুডলস", "Dim Noodles", "bhaji", ["Noodles", "Egg"], "national", 78],
  ["egg-cheese-omelette", "চিজ অমলেট", "Cheese Omelette", "fry", ["Egg", "Cheese"], "national", 50],
  ["egg-shutki-dim-bhuna", "শুঁটকি ডিম ভুনা", "Shutki Dim Bhuna", "shutki", ["Dried fish", "Egg"], "chittagong", 48],

  // --- Vegetables -------------------------------------------------------------
  ["veg-alu-bharta", "আলু ভর্তা", "Alu Bharta", "bharta", ["Potato"], "national", 99],
  ["veg-alu-bhaji", "আলু ভাজি", "Alu Bhaji", "bhaji", ["Potato", "Onion"], "national", 97],
  ["veg-alur-jhol", "আলুর ঝোল", "Alur Jhol", "jhol", ["Potato", "Tomato"], "national", 88],
  ["veg-alur-dom", "আলুর দম", "Alur Dom", "bhuna", ["Potato", "Yogurt"], "national", 82],
  ["veg-begun-bharta", "বেগুন ভর্তা", "Begun Bharta", "bharta", ["Eggplant"], "national", 94],
  ["veg-beguni", "বেগুনি", "Beguni", "bora", ["Eggplant", "Gram flour"], "national", 90],
  ["veg-begun-bhaja", "বেগুন ভাজি", "Begun Bhaji", "fry", ["Eggplant"], "national", 88],
  ["veg-shukto", "শুক্তো", "Shukto", "torkari", ["Bitter gourd", "Bottle gourd", "Potato"], "national", 70],
  ["veg-charchari", "চচ্চড়ি", "Charchari", "torkari", ["Potato", "Pumpkin", "Radish"], "national", 74],
  ["veg-labra", "লাবড়া", "Labra", "torkari", ["Pumpkin", "Potato", "Eggplant"], "national", 66],
  ["veg-niramish", "নিরামিষ", "Niramish", "torkari", ["Cauliflower", "Potato", "Peas"], "national", 76],
  ["veg-kumra-torkari", "মিষ্টি কুমড়ার তরকারি", "Pumpkin Torkari", "torkari", ["Pumpkin", "Potato"], "national", 80],
  ["veg-fulkopi-bhaji", "ফুলকপি ভাজি", "Cauliflower Bhaji", "bhaji", ["Cauliflower", "Potato"], "national", 86],
  ["veg-badhakopi-torkari", "বাঁধাকপির তরকারি", "Cabbage Torkari", "torkari", ["Cabbage", "Potato"], "national", 84],
  ["veg-gajor-mula", "গাজর মুলার তরকারি", "Carrot Radish Torkari", "torkari", ["Carrot", "Radish"], "national", 60],
  ["veg-potol-bhaji", "পটোল ভাজি", "Potol Bhaji", "bhaji", ["Ridge gourd", "Potato"], "national", 72],
  ["veg-jhinge-torkari", "ঝিঙ্গার তরকারি", "Ridge Gourd Torkari", "torkari", ["Ridge gourd", "Potato"], "national", 68],
  ["veg-lau-torkari", "লাউয়ের তরকারি", "Lau Torkari", "torkari", ["Bottle gourd", "Potato"], "national", 82],
  ["veg-lau-ghonto", "লাউ ঘণ্ট", "Lau Ghonto", "torkari", ["Bottle gourd", "Coconut"], "national", 58],
  ["veg-dherosh-torkari", "ঢেঁড়সের তরকারি", "Okra Torkari", "torkari", ["Okra", "Potato"], "national", 74],
  ["veg-dherosh-bhaji", "ঢেঁড়স ভাজি", "Okra Bhaji", "bhaji", ["Okra", "Onion"], "national", 78],
  ["veg-lal-shak-bhaja", "লাল শাক ভাজা", "Lal Shak Bhaja", "bhaji", ["Red amaranth", "Garlic"], "national", 85],
  ["veg-palong-bhaji", "পালং শাক ভাজি", "Spinach Bhaji", "bhaji", ["Spinach", "Garlic"], "national", 84],
  ["veg-palong-chola", "পালং শাক দিয়ে ছোলা", "Spinach with Chickpeas", "torkari", ["Spinach", "Chickpeas"], "national", 58],
  ["veg-broccoli-bhaji", "ব্রকলি ভাজি", "Broccoli Bhaji", "bhaji", ["Broccoli", "Garlic"], "national", 46],
  ["veg-sim-torkari", "সিমের তরকারি", "Bean Torkari", "torkari", ["Green beans", "Potato"], "national", 72],
  ["veg-korola-bhaji", "করলা ভাজি", "Bitter Gourd Bhaji", "bhaji", ["Bitter gourd", "Onion"], "national", 70],
  ["veg-mula-bhaji", "মুলা ভাজি", "Radish Bhaji", "bhaji", ["Radish", "Onion"], "national", 62],
  ["veg-chalkumra-torkari", "চালকুমড়ার তরকারি", "Ash Gourd Torkari", "torkari", ["Ash gourd", "Potato"], "national", 56],
  ["veg-sojne-torkari", "সজনে ডাঁটার তরকারি", "Drumstick Torkari", "torkari", ["Drumstick", "Potato"], "national", 64],
  ["veg-kochu-bhuna", "কচু ভুনা", "Taro Bhuna", "bhuna", ["Taro root", "Onion"], "national", 60],
  ["veg-kochur-loti", "কচুর লতি", "Kochur Loti", "torkari", ["Taro root", "Prawn"], "national", 68],
  ["veg-mishti-alu-bhaji", "মিষ্টি আলু ভাজি", "Sweet Potato Bhaji", "bhaji", ["Sweet potato", "Onion"], "national", 52],
  ["veg-echor-torkari", "এঁচোড়ের তরকারি", "Jackfruit Torkari", "torkari", ["Jackfruit (raw)", "Potato"], "national", 58],
  ["veg-pepe-torkari", "কাঁচা পেঁপের তরকারি", "Raw Papaya Torkari", "torkari", ["Papaya (raw)", "Potato"], "national", 62],
  ["veg-mocha-ghonto", "মোচার ঘণ্ট", "Mocha Ghonto", "torkari", ["Banana flower", "Potato"], "national", 44],
  ["veg-mushroom-bhuna", "মাশরুম ভুনা", "Mushroom Bhuna", "bhuna", ["Mushroom", "Onion"], "national", 42],
  ["veg-capsicum-bhaji", "ক্যাপসিকাম ভাজি", "Capsicum Bhaji", "bhaji", ["Capsicum", "Onion"], "national", 40],
  ["veg-matar-torkari", "মটরশুঁটির তরকারি", "Peas Torkari", "torkari", ["Peas", "Potato"], "national", 60],
  ["veg-beet-bhaji", "বিটরুট ভাজি", "Beetroot Bhaji", "bhaji", ["Beetroot", "Onion"], "national", 34],
  ["veg-tomato-bharta", "টমেটো ভর্তা", "Tomato Bharta", "bharta", ["Tomato"], "national", 76],
  ["veg-sobji-khichuri", "সবজি খিচুড়ি", "Sobji Khichuri", "khichuri", ["Rice", "Mung dal", "Carrot"], "national", 84],
  ["veg-mixed-sobji", "মিক্সড সবজি", "Mixed Sobji", "torkari", ["Carrot", "Green beans", "Cauliflower"], "national", 78],
  ["veg-alu-fulkopi", "আলু ফুলকপির তরকারি", "Potato Cauliflower Torkari", "torkari", ["Potato", "Cauliflower"], "national", 86],
  ["veg-pui-shak", "পুঁই শাক ভাজি", "Pui Shak Bhaji", "bhaji", ["Spinach", "Onion"], "national", 66],
  ["veg-shosha-salad", "শসার সালাদ", "Cucumber Salad", "snack", ["Cucumber", "Onion"], "national", 80],

  // --- Lentils -----------------------------------------------------------------
  ["dal-musur-dal", "মুসুর ডাল", "Musur Dal", "dal", ["Red lentils"], "national", 98],
  ["dal-mug-dal", "মুগ ডাল", "Mug Dal", "dal", ["Mung dal"], "national", 90],
  ["dal-bhaja-mug-dal", "ভাজা মুগ ডাল", "Roasted Mug Dal", "dal", ["Mung dal", "Coconut"], "national", 74],
  ["dal-cholar-dal", "ছোলার ডাল", "Cholar Dal", "dal", ["Split chickpeas", "Coconut"], "national", 84],
  ["dal-mashkalai-dal", "মাসকলাই ডাল", "Mashkalai Dal", "dal", ["Mung dal", "Garlic"], "rangpur", 72],
  ["dal-mashkalai-bhuna", "মাসকলাই ভুনা", "Mashkalai Bhuna", "bhuna", ["Mung dal", "Onion"], "rangpur", 56],
  ["dal-mishro-dal", "মিশ্র ডাল", "Mixed Dal", "dal", ["Red lentils", "Mung dal"], "national", 70],
  ["dal-dal-bhuna", "ডাল ভুনা", "Dal Bhuna", "bhuna", ["Red lentils", "Onion"], "national", 76],
  ["dal-dal-bhaji", "ডাল ভাজি", "Dal Bhaji", "bhaji", ["Red lentils", "Onion"], "national", 62],
  ["dal-dal-bora", "ডালের বড়া", "Daler Bora", "bora", ["Red lentils"], "national", 72],
  ["dal-alu-dal", "আলু দিয়ে ডাল", "Dal with Potato", "dal", ["Red lentils", "Potato"], "national", 82],
  ["dal-lau-dal", "লাউ দিয়ে ডাল", "Dal with Bottle Gourd", "dal", ["Red lentils", "Bottle gourd"], "national", 74],
  ["dal-palong-dal", "পালং শাক দিয়ে ডাল", "Dal with Spinach", "dal", ["Red lentils", "Spinach"], "national", 66],
  ["dal-macher-matha-dal", "মাছের মাথা দিয়ে ডাল", "Dal with Fish Head", "dal", ["Mung dal", "Rui fish"], "national", 68],
  ["dal-chola-bhuna", "ছোলা ভুনা", "Chola Bhuna", "bhuna", ["Chickpeas", "Onion"], "national", 86],
  ["dal-rajma-curry", "রাজমা কারি", "Rajma Curry", "curry", ["Kidney beans", "Onion"], "national", 44],
  ["dal-musur-khichuri", "মুসুর ডালের খিচুড়ি", "Musur Dal Khichuri", "khichuri", ["Rice", "Red lentils"], "national", 92],
  ["dal-mug-khichuri", "মুগ ডালের খিচুড়ি", "Mug Dal Khichuri", "khichuri", ["Rice", "Mung dal"], "national", 90],

  // --- Rice dishes ---------------------------------------------------------------
  ["rice-polao", "পোলাও", "Polao", "polao", ["Rice"], "national", 92],
  ["rice-lachcha-polao", "লাচ্ছা পোলাও", "Lachcha Polao", "polao", ["Rice", "Ghee"], "national", 62],
  ["rice-sobji-polao", "সবজি পোলাও", "Sobji Polao", "polao", ["Rice", "Carrot", "Peas"], "national", 72],
  ["rice-chingri-polao", "চিংড়ি পোলাও", "Chingri Polao", "polao", ["Rice", "Prawn"], "national", 66],
  ["rice-sada-bhat", "সাদা ভাত", "Sada Bhat", "polao", ["Rice"], "national", 99],
  ["rice-bhaja-bhat", "ভাজা ভাত", "Bhaja Bhat", "bhaji", ["Cooked rice", "Egg", "Carrot"], "national", 80],
  ["rice-murgi-tehari", "মুরগির তেহারি", "Chicken Tehari", "biryani", ["Chicken", "Rice"], "dhaka", 80],
  ["rice-ilish-polao", "ইলিশ পোলাও", "Ilish Polao", "polao", ["Rice", "Hilsa"], "national", 70],
  ["rice-lal-bhat", "লাল চালের ভাত", "Lal Chaler Bhat", "polao", ["Rice"], "national", 58],

  // --- Dhaka street & snacks ------------------------------------------------------
  ["snk-fuchka", "ফুচকা", "Fuchka", "snack", ["Potato", "Chickpeas", "Tamarind"], "dhaka", 92],
  ["snk-chotpoti", "চটপটি", "Chotpoti", "snack", ["Chickpeas", "Potato", "Egg"], "dhaka", 90],
  ["snk-jhalmuri", "ঝালমুড়ি", "Jhalmuri", "snack", ["Puffed rice", "Onion", "Green chilli"], "dhaka", 94],
  ["snk-alur-chop", "আলুর চপ", "Alur Chop", "chop", ["Potato", "Onion"], "national", 88],
  ["snk-piyaju", "পেঁয়াজু", "Piyaju", "bora", ["Onion", "Red lentils"], "national", 92],
  ["snk-singara", "সিঙ্গারা", "Singara", "chop", ["Potato", "Peas", "Maida"], "national", 90],
  ["snk-samucha", "সমুচা", "Samucha", "chop", ["Beef", "Maida", "Onion"], "national", 84],
  ["snk-doi-bora", "দই বড়া", "Doi Bora", "bora", ["Red lentils", "Yogurt"], "dhaka", 58],
  ["snk-chola-muri", "ছোলা মুড়ি", "Chola Muri", "snack", ["Chickpeas", "Puffed rice"], "national", 74],
  ["snk-dabli", "ডাবলি", "Dabli", "snack", ["Chickpeas", "Onion"], "chittagong", 62],
  ["snk-kima-porota", "কিমা পরোটা", "Kima Porota", "bread", ["Flour", "Beef"], "dhaka", 66],
  ["snk-sobji-chop", "সবজি চপ", "Sobji Chop", "chop", ["Carrot", "Potato", "Green beans"], "national", 58],
  ["snk-mughlai-porota", "মোগলাই পরোটা", "Mughlai Porota", "bread", ["Maida", "Egg", "Beef"], "dhaka", 72],
  ["snk-nimki", "নিমকি", "Nimki", "bread", ["Maida"], "national", 54],
  ["snk-sobji-pakora", "সবজি পাকোড়া", "Sobji Pakora", "bora", ["Cabbage", "Gram flour"], "national", 64],

  // --- Breads -----------------------------------------------------------------------
  ["brd-ruti", "রুটি", "Ruti", "bread", ["Flour"], "national", 97],
  ["brd-porota", "পরোটা", "Porota", "bread", ["Flour"], "national", 96],
  ["brd-nan-ruti", "নান রুটি", "Nan Ruti", "bread", ["Maida", "Yogurt"], "national", 74],
  ["brd-chapati", "চাপাতি", "Chapati", "bread", ["Flour"], "national", 82],
  ["brd-puri", "পুরি", "Puri", "bread", ["Flour"], "national", 80],
  ["brd-dim-porota", "ডিম পরোটা", "Dim Porota", "bread", ["Flour", "Egg"], "national", 78],
  ["brd-alur-porota", "আলুর পরোটা", "Alur Porota", "bread", ["Flour", "Potato"], "national", 84],
  ["brd-sobji-ruti", "সবজি রুটি", "Sobji Ruti", "bread", ["Flour", "Carrot"], "national", 46],
  ["brd-tandoori-nan", "তন্দুরি নান", "Tandoori Nan", "bread", ["Maida", "Milk"], "national", 60],

  // --- Sweets -------------------------------------------------------------------------
  ["swt-firni", "ফিরনি", "Firni", "sweet", ["Rice", "Milk"], "national", 86],
  ["swt-shahi-tukra", "শাহি টুকরা", "Shahi Tukra", "sweet", ["Bread", "Milk"], "dhaka", 58],
  ["swt-narikel-naru", "নারকেলের নাড়ু", "Narikel Naru", "sweet", ["Coconut", "Jaggery"], "national", 78],
  ["swt-chaler-payesh", "চালের পায়েস", "Chaler Payesh", "sweet", ["Rice", "Milk"], "national", 88],
  ["swt-gajorer-halua", "গাজরের হালুয়া", "Gajorer Halua", "sweet", ["Carrot", "Milk"], "national", 74],
  ["swt-sujir-halua", "সুজির হালুয়া", "Sujir Halua", "sweet", ["Semolina", "Milk"], "national", 82],
  ["swt-dimer-halua", "ডিমের হালুয়া", "Dimer Halua", "sweet", ["Egg", "Milk"], "national", 60],
  ["swt-patishapta", "পাটিসাপটা পিঠা", "Patishapta Pitha", "sweet", ["Flour", "Coconut", "Milk"], "national", 76],
  ["swt-bhapa-pitha", "ভাপা পিঠা", "Bhapa Pitha", "sweet", ["Rice", "Jaggery", "Coconut"], "national", 84],
  ["swt-chitoi-pitha", "চিতই পিঠা", "Chitoi Pitha", "sweet", ["Rice"], "national", 80],

  // --- More authentic everyday & festive dishes -----------------------------
  ["add-mocha-ghonto", "মোচার ঘণ্ট", "Mocha Ghonto", "torkari", ["Banana flower", "Potato"], "national", 68],
  ["add-thor-ghonto", "থোড় ঘণ্ট", "Thor Ghonto", "torkari", ["Banana stem", "Coconut"], "national", 60],
  ["add-kathal-bichi-bhuna", "কাঁঠাল বিচি ভুনা", "Jackfruit Seed Bhuna", "bhuna", ["Jackfruit seed", "Dried fish"], "national", 64],
  ["add-kochu-shak-bhaji", "কচু শাক ভাজি", "Kochu Shak Bhaji", "bhaji", ["Taro leaves"], "national", 70],
  ["add-kochur-mukhi-bhuna", "কচুর মুখি ভুনা", "Kochur Mukhi Bhuna", "bhuna", ["Taro root", "Onion"], "national", 66],
  ["add-kolmi-shak-bhaji", "কলমি শাক ভাজি", "Kolmi Shak Bhaji", "bhaji", ["Water spinach"], "national", 72],
  ["add-helencha-bhaji", "হেলেঞ্চা শাক ভাজি", "Helencha Shak Bhaji", "bhaji", ["Helencha leaves"], "national", 52],
  ["add-danta-chocchori", "ডাঁটা চচ্চড়ি", "Danta Chorchori", "torkari", ["Drumstick", "Potato"], "national", 66],
  ["add-sojne-pata-bhaji", "সজনে পাতার ভাজি", "Sojne Pata Bhaji", "bhaji", ["Drumstick leaves"], "national", 58],
  ["add-borboti-bhaji", "বরবটি ভাজি", "Borboti Bhaji", "bhaji", ["Yardlong beans"], "national", 71],
  ["add-kacha-kola-torkari", "কাঁচকলার তরকারি", "Green Banana Torkari", "torkari", ["Green banana", "Potato"], "national", 69],
  ["add-kacha-kola-bharta", "কাঁচকলা ভর্তা", "Green Banana Bharta", "bharta", ["Green banana"], "national", 63],
  ["add-pepe-bhaji", "পেঁপে ভাজি", "Pepe Bhaji", "bhaji", ["Papaya (raw)"], "national", 67],
  ["add-chalkumra-bora", "চালকুমড়ার বড়া", "Chalkumra Bora", "bora", ["Ash gourd"], "national", 55],
  ["add-potol-dolma", "পটোলের দোলমা", "Potoler Dolma", "torkari", ["Pointed gourd", "Prawn"], "national", 65],
  ["add-potol-bharta", "পটোল ভর্তা", "Potol Bharta", "bharta", ["Pointed gourd"], "national", 57],
  ["add-jhinge-posto", "ঝিঙে পোস্ত", "Jhinge Posto", "torkari", ["Ridge gourd", "Poppy seed"], "national", 62],
  ["add-alu-posto", "আলু পোস্ত", "Alu Posto", "torkari", ["Potato", "Poppy seed"], "national", 74],
  ["add-shim-bharta", "শিম ভর্তা", "Shim Bharta", "bharta", ["Beans"], "national", 58],
  ["add-taki-bharta", "টাকি মাছের ভর্তা", "Taki Macher Bharta", "bharta", ["Taki fish"], "national", 73],
  ["add-shidol-bharta", "শিদল ভর্তা", "Shidol Bharta", "bharta", ["Dried fish"], "sylhet", 61],
  ["add-kalojira-bharta", "কালিজিরা ভর্তা", "Kalojira Bharta", "bharta", ["Nigella seed"], "national", 54],
  ["add-shorshe-bharta", "সরিষা ভর্তা", "Shorshe Bharta", "bharta", ["Mustard seed"], "national", 56],
  ["add-rosun-bharta", "রসুন ভর্তা", "Rosun Bharta", "bharta", ["Garlic"], "national", 64],
  ["add-morich-bharta", "মরিচ ভর্তা", "Morich Bharta", "bharta", ["Green chilli"], "national", 66],
  ["add-dhonepata-bharta", "ধনেপাতা ভর্তা", "Dhonepata Bharta", "bharta", ["Coriander leaves"], "national", 62],
  ["add-til-bharta", "তিল ভর্তা", "Til Bharta", "bharta", ["Sesame"], "national", 53],
  ["add-narkel-bharta", "নারকেল ভর্তা", "Narkel Bharta", "bharta", ["Coconut"], "national", 57],
  ["add-misti-kumra-bharta", "মিষ্টি কুমড়ার ভর্তা", "Misti Kumra Bharta", "bharta", ["Pumpkin"], "national", 59],
  ["add-dal-bharta", "ডাল ভর্তা", "Dal Bharta", "bharta", ["Red lentils"], "national", 68],
  ["add-chapa-shutki-bharta", "চ্যাপা শুঁটকি ভর্তা", "Chapa Shutki Bharta", "shutki", ["Dried fish", "Green chilli"], "mymensingh", 70],
  ["add-churi-shutki-bhuna", "ছুরি শুঁটকি ভুনা", "Churi Shutki Bhuna", "shutki", ["Dried fish", "Onion"], "chittagong", 67],
  ["add-koral-bhaja", "কোরাল মাছ ভাজা", "Koral Mach Bhaja", "fry", ["Koral fish"], "national", 66],
  ["add-koral-jhol", "কোরাল মাছের ঝোল", "Koral Macher Jhol", "jhol", ["Koral fish", "Potato"], "national", 64],
  ["add-tengra-jhol", "টেংরা মাছের ঝোল", "Tengra Macher Jhol", "jhol", ["Tengra fish", "Potato"], "national", 72],
  ["add-tengra-bhuna", "টেংরা মাছ ভুনা", "Tengra Mach Bhuna", "bhuna", ["Tengra fish", "Onion"], "national", 68],
  ["add-shing-jhol", "শিং মাছের ঝোল", "Shing Macher Jhol", "jhol", ["Shing fish", "Potato"], "national", 74],
  ["add-magur-jhol", "মাগুর মাছের ঝোল", "Magur Macher Jhol", "jhol", ["Magur fish", "Potato"], "national", 70],
  ["add-koi-tel-jhal", "কই মাছের তেল ঝাল", "Koi Macher Tel Jhal", "bhuna", ["Koi fish", "Green chilli"], "national", 69],
  ["add-koi-dopeyaja", "কই মাছের দোপেঁয়াজা", "Koi Macher Dopeyaja", "dopeyaja", ["Koi fish", "Onion"], "national", 63],
  ["add-bele-jhol", "বেলে মাছের ঝোল", "Bele Macher Jhol", "jhol", ["Bele fish", "Potato"], "national", 58],
  ["add-sarputi-bhaja", "সরপুঁটি মাছ ভাজা", "Sarputi Mach Bhaja", "fry", ["Sarputi fish"], "national", 60],
  ["add-ilish-korma", "ইলিশ কোরমা", "Ilish Korma", "curry", ["Hilsa", "Yogurt"], "national", 66],
  ["add-ilish-khichuri", "ইলিশ খিচুড়ি", "Ilish Khichuri", "khichuri", ["Rice", "Mung dal", "Hilsa"], "national", 78],
  ["add-ilish-bhuna", "ইলিশ ভুনা", "Ilish Bhuna", "bhuna", ["Hilsa", "Onion"], "national", 80],
  ["add-ilish-dopeyaja", "ইলিশ দোপেঁয়াজা", "Ilish Dopeyaja", "dopeyaja", ["Hilsa", "Onion"], "national", 71],
  ["add-chingri-dopeyaja", "চিংড়ি দোপেঁয়াজা", "Chingri Dopeyaja", "dopeyaja", ["Prawn", "Onion"], "national", 69],
  ["add-kakra-bhuna", "কাঁকড়া ভুনা", "Kakra Bhuna", "bhuna", ["Crab", "Onion"], "chittagong", 62],
  ["add-kucho-chingri-bhuna", "কুঁচো চিংড়ি ভুনা", "Kucho Chingri Bhuna", "bhuna", ["Prawn", "Onion"], "national", 64],
  ["add-chingri-kabab", "চিংড়ি কাবাব", "Chingri Kabab", "kabab", ["Prawn", "Onion"], "national", 60],
  ["add-macher-kabab", "মাছের কাবাব", "Macher Kabab", "kabab", ["Rui fish", "Onion"], "national", 61],
  ["add-murgir-kima-kabab", "মুরগির কিমা কাবাব", "Murgir Kima Kabab", "kabab", ["Chicken mince", "Onion"], "national", 66],
  ["add-gorur-kima-bhuna", "গরুর কিমা ভুনা", "Gorur Kima Bhuna", "bhuna", ["Beef mince", "Onion"], "national", 70],
  ["add-bhuri-bhuna", "গরুর ভুঁড়ি ভুনা", "Gorur Bhuri Bhuna", "bhuna", ["Tripe", "Onion"], "national", 58],
  ["add-mogoj-bhuna", "গরুর মগজ ভুনা", "Gorur Mogoj Bhuna", "bhuna", ["Brain", "Onion"], "national", 57],
  ["add-murgir-kolija-bhuna", "মুরগির কলিজা ভুনা", "Murgir Kolija Bhuna", "bhuna", ["Chicken liver", "Onion"], "national", 67],
  ["add-gila-kolija-bhuna", "গিলা কলিজা ভুনা", "Gila Kolija Bhuna", "bhuna", ["Chicken liver", "Onion"], "national", 63],
  ["add-hansher-dim-bhuna", "হাঁসের ডিম ভুনা", "Hansher Dim Bhuna", "bhuna", ["Duck egg", "Onion"], "national", 59],
  ["add-kobutor-roast", "কবুতরের রোস্ট", "Kobutor Roast", "curry", ["Pigeon", "Yogurt"], "national", 55],
  ["add-koyel-bhuna", "কোয়েল পাখির ভুনা", "Koyel Pakhir Bhuna", "bhuna", ["Quail", "Onion"], "national", 52],
  ["add-khashir-paya", "খাসির পায়া", "Khashir Paya", "curry", ["Trotters", "Onion"], "national", 68],
  ["add-khashir-khichuri", "খাসির খিচুড়ি", "Khashir Khichuri", "khichuri", ["Rice", "Mung dal", "Mutton"], "national", 74],
  ["add-beef-khichuri", "গরুর মাংসের খিচুড়ি", "Beef Khichuri", "khichuri", ["Rice", "Mung dal", "Beef"], "national", 76],
  ["add-murgir-khichuri", "মুরগির খিচুড়ি", "Murgir Khichuri", "khichuri", ["Rice", "Mung dal", "Chicken"], "national", 82],
  ["add-hansher-khichuri", "হাঁসের ভুনা খিচুড়ি", "Hansher Bhuna Khichuri", "khichuri", ["Rice", "Mung dal", "Duck"], "national", 70],
  ["add-achari-murgi", "আচারি মুরগি", "Achari Murgi", "bhuna", ["Chicken", "Pickle"], "national", 72],
  ["add-achari-gosht", "আচারি গোশত", "Achari Gosht", "bhuna", ["Beef", "Pickle"], "national", 68],
  ["add-lebu-murgi", "লেবু মুরগি", "Lebu Murgi", "bhuna", ["Chicken", "Lemon"], "national", 58],
  ["add-narkel-dudhe-murgi", "নারকেল দুধে মুরগি", "Narkel Dudhe Murgi", "malaikari", ["Chicken", "Coconut milk"], "national", 66],
  ["add-murgir-jhal-bhuna", "মুরগির ঝাল ভুনা", "Murgir Jhal Bhuna", "bhuna", ["Chicken", "Green chilli"], "national", 75],
  ["add-dim-korma", "ডিম কোরমা", "Dim Korma", "curry", ["Egg", "Yogurt"], "national", 67],
  ["add-dim-malaikari", "ডিমের মালাইকারি", "Dimer Malaikari", "malaikari", ["Egg", "Coconut milk"], "national", 62],
  ["add-dim-khichuri", "ডিম খিচুড়ি", "Dim Khichuri", "khichuri", ["Rice", "Mung dal", "Egg"], "national", 79],
  ["add-alu-dim-jhol", "আলু ডিমের ঝোল", "Alu Dimer Jhol", "jhol", ["Potato", "Egg"], "national", 80],
  ["add-dim-biryani", "ডিম বিরিয়ানি", "Dim Biryani", "biryani", ["Egg", "Rice", "Yogurt"], "national", 70],
  ["add-sobji-biryani", "সবজি বিরিয়ানি", "Sobji Biryani", "biryani", ["Mixed vegetables", "Rice", "Yogurt"], "national", 65],
  ["add-mach-biryani", "মাছের বিরিয়ানি", "Macher Biryani", "biryani", ["Rui fish", "Rice", "Yogurt"], "national", 61],
  ["add-chingri-biryani", "চিংড়ি বিরিয়ানি", "Chingri Biryani", "biryani", ["Prawn", "Rice", "Yogurt"], "national", 63],
  ["add-alu-begun-torkari", "আলু বেগুনের তরকারি", "Alu Beguner Torkari", "torkari", ["Potato", "Eggplant"], "national", 76],
  ["add-alu-kopi-jhol", "আলু কপির ঝোল", "Alu Kopir Jhol", "jhol", ["Potato", "Cauliflower"], "national", 78],
  ["add-alu-potol-torkari", "আলু পটোলের তরকারি", "Alu Potoler Torkari", "torkari", ["Potato", "Pointed gourd"], "national", 74],
  ["add-alu-motor-torkari", "আলু মটরের তরকারি", "Alu Motor Torkari", "torkari", ["Potato", "Peas"], "national", 73],
  ["add-paneer-torkari", "পনিরের তরকারি", "Paneer Torkari", "torkari", ["Cottage cheese", "Tomato"], "national", 60],
  ["add-chanar-kofta", "ছানার কোফতা", "Chanar Kofta", "bora", ["Cottage cheese", "Potato"], "national", 58],
  ["add-soyabean-bhuna", "সয়াবিন ভুনা", "Soyabean Bhuna", "bhuna", ["Soybean", "Onion"], "national", 62],
  ["add-mashroom-bhuna", "মাশরুম ভুনা", "Mushroom Bhuna", "bhuna", ["Mushroom", "Onion"], "national", 57],
  ["add-fulkopir-roast", "ফুলকপির রোস্ট", "Fulkopir Roast", "fry", ["Cauliflower"], "national", 59],
  ["add-amrar-dal", "আমড়ার ডাল", "Amrar Dal", "dal", ["Red lentils", "Hog plum"], "national", 61],
  ["add-tomato-dal", "টমেটো ডাল", "Tomato Dal", "dal", ["Red lentils", "Tomato"], "national", 72],
  ["add-lau-patar-paturi", "লাউ পাতার পাতুরি", "Lau Patar Paturi", "patuari", ["Bottle gourd leaves", "Mustard seed"], "national", 56],
  ["add-kumro-phuler-bora", "কুমড়ো ফুলের বড়া", "Kumro Phuler Bora", "bora", ["Pumpkin flower", "Gram flour"], "national", 58],
  ["add-peyaj-koli-bhaji", "পেঁয়াজ কলি ভাজি", "Peyaj Koli Bhaji", "bhaji", ["Spring onion"], "national", 66],
  ["add-methi-shak-bhaji", "মেথি শাক ভাজি", "Methi Shak Bhaji", "bhaji", ["Fenugreek leaves"], "national", 55],
  ["add-shorishar-shak", "সরিষা শাক ভাজি", "Shorishar Shak Bhaji", "bhaji", ["Mustard leaves"], "national", 57],
  ["add-lau-shak-bhaji", "লাউ শাক ভাজি", "Lau Shak Bhaji", "bhaji", ["Bottle gourd leaves"], "national", 64],
  ["add-chirar-polao", "চিড়ার পোলাও", "Chirar Polao", "polao", ["Flattened rice", "Peas"], "national", 54],
  ["add-chira-bhaja", "চিড়া ভাজা", "Chira Bhaja", "snack", ["Flattened rice", "Peanut"], "national", 62],
  ["add-murir-moa", "মুড়ির মোয়া", "Murir Moa", "sweet", ["Puffed rice", "Jaggery"], "national", 70],
  ["add-tiler-naru", "তিলের নাড়ু", "Tiler Naru", "sweet", ["Sesame", "Jaggery"], "national", 66],
  ["add-taler-pitha", "তালের পিঠা", "Taler Pitha", "sweet", ["Palm fruit", "Rice"], "national", 68],
  ["add-taler-bora", "তালের বড়া", "Taler Bora", "sweet", ["Palm fruit", "Flour"], "national", 64],
  ["add-kolar-bora", "কলার বড়া", "Kolar Bora", "sweet", ["Banana", "Flour"], "national", 65],
  ["add-narkel-puli", "নারকেলের পুলি পিঠা", "Narkel Puli Pitha", "sweet", ["Coconut", "Rice", "Jaggery"], "national", 69],
  ["add-gurer-payesh", "গুড়ের পায়েস", "Gurer Payesh", "sweet", ["Rice", "Milk", "Jaggery"], "national", 77],
  ["add-dudh-semai", "দুধ সেমাই", "Dudh Semai", "sweet", ["Semolina", "Milk"], "national", 80],
];


function buildCurated(): DbRecipe[] {
  return CURATED.map(([id, nameBn, nameEn, method, ingredients, region, popularity]) => {
    const spec = M[method];
    const headBn = bn(ingredients[0]!);
    const headEn = ingredients[0]!.toLowerCase();
    return {
      id: `cur-${id}`,
      name_bn: nameBn,
      name_en: nameEn,
      ingredients,
      staples: spec.staples.filter((s) => !ingredients.includes(s)),
      steps_bn: spec.stepsBn(headBn),
      steps_en: spec.stepsEn(headEn),
      cookTime: spec.cookTime,
      difficulty: spec.difficulty as Difficulty,
      spiceLevel: spec.spiceLevel as SpiceLevel,
      tags: [...spec.tags, region],
      region,
      popularity,
    };
  });
}

/** Curated authentic regional dishes only — no generated combinations. */
export const REGIONAL_RECIPES: DbRecipe[] = buildCurated();

