// Authentic American home-cooking dish names.
//
// Same law as the Bengali database: these are real dishes that Americans
// actually cook and eat. The AI may only name a recipe with a dish of this
// kind — never an invented fusion name.

export type AmericanRecipe = { name: string; ingredients: string[] };

export const AMERICAN_RECIPES: AmericanRecipe[] = [
  { name: "Scrambled Eggs", ingredients: ["egg", "butter", "milk"] },
  { name: "Cheese Omelette", ingredients: ["egg", "cheese", "butter"] },
  { name: "Buttermilk Pancakes", ingredients: ["flour", "buttermilk", "egg", "butter"] },
  { name: "Waffles", ingredients: ["flour", "egg", "milk", "butter"] },
  { name: "French Toast", ingredients: ["bread", "egg", "milk", "cinnamon"] },
  { name: "Biscuits and Gravy", ingredients: ["flour", "sausage", "milk", "butter"] },
  { name: "Hash Browns", ingredients: ["potato", "onion", "butter"] },
  { name: "Home Fries", ingredients: ["potato", "onion", "pepper"] },
  { name: "Breakfast Burrito", ingredients: ["tortilla", "egg", "cheese", "sausage"] },
  { name: "Eggs Benedict", ingredients: ["egg", "english muffin", "ham", "butter"] },
  { name: "Sausage and Eggs", ingredients: ["sausage", "egg"] },
  { name: "Bacon and Eggs", ingredients: ["bacon", "egg"] },
  { name: "Oatmeal", ingredients: ["oats", "milk", "brown sugar"] },
  { name: "Blueberry Muffins", ingredients: ["flour", "blueberry", "sugar", "egg"] },
  { name: "Banana Bread", ingredients: ["banana", "flour", "sugar", "egg"] },
  { name: "Cinnamon Rolls", ingredients: ["flour", "cinnamon", "butter", "sugar"] },
  { name: "Cheeseburger", ingredients: ["ground beef", "cheese", "bun", "onion"] },
  { name: "Bacon Cheeseburger", ingredients: ["ground beef", "bacon", "cheese", "bun"] },
  { name: "Sloppy Joes", ingredients: ["ground beef", "tomato sauce", "onion", "bun"] },
  { name: "Meatloaf", ingredients: ["ground beef", "breadcrumbs", "egg", "ketchup"] },
  { name: "Salisbury Steak", ingredients: ["ground beef", "onion", "mushroom", "gravy"] },
  { name: "Beef Stew", ingredients: ["beef", "potato", "carrot", "onion"] },
  { name: "Pot Roast", ingredients: ["beef chuck", "carrot", "potato", "onion"] },
  { name: "Chili con Carne", ingredients: ["ground beef", "beans", "tomato", "chili powder"] },
  { name: "Beef Tacos", ingredients: ["ground beef", "tortilla", "cheese", "lettuce"] },
  { name: "Philly Cheesesteak", ingredients: ["beef", "onion", "pepper", "cheese", "roll"] },
  { name: "Steak and Potatoes", ingredients: ["steak", "potato", "butter", "garlic"] },
  { name: "Beef Stroganoff", ingredients: ["beef", "mushroom", "sour cream", "noodles"] },
  { name: "Shepherd's Pie", ingredients: ["ground beef", "potato", "peas", "carrot"] },
  { name: "Corned Beef Hash", ingredients: ["corned beef", "potato", "onion"] },
  { name: "Fried Chicken", ingredients: ["chicken", "flour", "buttermilk", "oil"] },
  { name: "Buffalo Wings", ingredients: ["chicken wings", "hot sauce", "butter"] },
  { name: "Chicken Pot Pie", ingredients: ["chicken", "carrot", "peas", "pie crust"] },
  { name: "Chicken Noodle Soup", ingredients: ["chicken", "noodles", "carrot", "celery"] },
  { name: "Chicken and Dumplings", ingredients: ["chicken", "flour", "milk", "celery"] },
  { name: "Baked Chicken Thighs", ingredients: ["chicken thighs", "garlic", "paprika", "oil"] },
  { name: "Roast Chicken", ingredients: ["whole chicken", "butter", "lemon", "herbs"] },
  { name: "Chicken Parmesan", ingredients: ["chicken breast", "tomato sauce", "mozzarella", "breadcrumbs"] },
  { name: "Chicken Alfredo", ingredients: ["chicken", "fettuccine", "cream", "parmesan"] },
  { name: "Chicken Caesar Salad", ingredients: ["chicken", "romaine", "parmesan", "croutons"] },
  { name: "Chicken Quesadilla", ingredients: ["chicken", "tortilla", "cheese", "pepper"] },
  { name: "Chicken Fajitas", ingredients: ["chicken", "pepper", "onion", "tortilla"] },
  { name: "BBQ Chicken", ingredients: ["chicken", "barbecue sauce", "paprika"] },
  { name: "Chicken Tenders", ingredients: ["chicken", "flour", "egg", "breadcrumbs"] },
  { name: "Turkey Sandwich", ingredients: ["turkey", "bread", "lettuce", "mayonnaise"] },
  { name: "Roast Turkey", ingredients: ["turkey", "butter", "herbs", "onion"] },
  { name: "Turkey Chili", ingredients: ["ground turkey", "beans", "tomato", "chili powder"] },
  { name: "Pulled Pork", ingredients: ["pork shoulder", "barbecue sauce", "onion"] },
  { name: "Baby Back Ribs", ingredients: ["pork ribs", "barbecue sauce", "brown sugar"] },
  { name: "Pork Chops with Applesauce", ingredients: ["pork chops", "apple", "butter"] },
  { name: "Baked Ham", ingredients: ["ham", "brown sugar", "mustard"] },
  { name: "Bacon Wrapped Meatloaf", ingredients: ["ground beef", "bacon", "ketchup", "egg"] },
  { name: "Sausage and Peppers", ingredients: ["sausage", "pepper", "onion"] },
  { name: "Corn Dogs", ingredients: ["hot dog", "cornmeal", "flour", "oil"] },
  { name: "Chicago Hot Dog", ingredients: ["hot dog", "bun", "relish", "onion"] },
  { name: "Grilled Cheese Sandwich", ingredients: ["bread", "cheese", "butter"] },
  { name: "Tuna Melt", ingredients: ["tuna", "bread", "cheese", "mayonnaise"] },
  { name: "Club Sandwich", ingredients: ["bread", "turkey", "bacon", "lettuce"] },
  { name: "BLT Sandwich", ingredients: ["bacon", "lettuce", "tomato", "bread"] },
  { name: "Peanut Butter and Jelly Sandwich", ingredients: ["bread", "peanut butter", "jam"] },
  { name: "Egg Salad Sandwich", ingredients: ["egg", "mayonnaise", "bread", "celery"] },
  { name: "Chicken Salad Sandwich", ingredients: ["chicken", "mayonnaise", "celery", "bread"] },
  { name: "Lobster Roll", ingredients: ["lobster", "mayonnaise", "roll", "lemon"] },
  { name: "Sloppy Grilled Cheese", ingredients: ["bread", "cheese", "ground beef"] },
  { name: "Clam Chowder", ingredients: ["clams", "potato", "cream", "bacon"] },
  { name: "Corn Chowder", ingredients: ["corn", "potato", "cream", "onion"] },
  { name: "Tomato Soup", ingredients: ["tomato", "cream", "onion", "basil"] },
  { name: "Split Pea Soup", ingredients: ["split peas", "ham", "carrot", "onion"] },
  { name: "Minestrone Soup", ingredients: ["beans", "pasta", "tomato", "vegetables"] },
  { name: "Gumbo", ingredients: ["sausage", "shrimp", "okra", "rice"] },
  { name: "Jambalaya", ingredients: ["rice", "sausage", "shrimp", "pepper"] },
  { name: "Shrimp and Grits", ingredients: ["shrimp", "grits", "cheese", "bacon"] },
  { name: "Fried Catfish", ingredients: ["catfish", "cornmeal", "oil"] },
  { name: "Crab Cakes", ingredients: ["crab", "breadcrumbs", "egg", "mayonnaise"] },
  { name: "Baked Salmon", ingredients: ["salmon", "lemon", "butter", "dill"] },
  { name: "Fish and Chips", ingredients: ["cod", "flour", "potato", "oil"] },
  { name: "Tuna Casserole", ingredients: ["tuna", "noodles", "peas", "cream soup"] },
  { name: "Shrimp Scampi", ingredients: ["shrimp", "garlic", "butter", "pasta"] },
  { name: "Macaroni and Cheese", ingredients: ["macaroni", "cheddar", "milk", "butter"] },
  { name: "Baked Ziti", ingredients: ["ziti", "tomato sauce", "ricotta", "mozzarella"] },
  { name: "Spaghetti and Meatballs", ingredients: ["spaghetti", "ground beef", "tomato sauce"] },
  { name: "Lasagna", ingredients: ["lasagna noodles", "ground beef", "ricotta", "mozzarella"] },
  { name: "Fettuccine Alfredo", ingredients: ["fettuccine", "cream", "parmesan", "butter"] },
  { name: "Pepperoni Pizza", ingredients: ["pizza dough", "tomato sauce", "mozzarella", "pepperoni"] },
  { name: "Cheese Pizza", ingredients: ["pizza dough", "tomato sauce", "mozzarella"] },
  { name: "Stuffed Shells", ingredients: ["pasta shells", "ricotta", "tomato sauce", "spinach"] },
  { name: "Chicken Casserole", ingredients: ["chicken", "rice", "cream soup", "cheese"] },
  { name: "Green Bean Casserole", ingredients: ["green beans", "cream soup", "fried onions"] },
  { name: "Tater Tot Casserole", ingredients: ["tater tots", "ground beef", "cheese"] },
  { name: "Breakfast Casserole", ingredients: ["egg", "sausage", "bread", "cheese"] },
  { name: "Mashed Potatoes", ingredients: ["potato", "butter", "milk"] },
  { name: "Scalloped Potatoes", ingredients: ["potato", "cream", "cheese", "onion"] },
  { name: "Baked Potato", ingredients: ["potato", "butter", "sour cream"] },
  { name: "French Fries", ingredients: ["potato", "oil", "salt"] },
  { name: "Sweet Potato Casserole", ingredients: ["sweet potato", "brown sugar", "pecans"] },
  { name: "Roasted Vegetables", ingredients: ["carrot", "broccoli", "olive oil"] },
  { name: "Corn on the Cob", ingredients: ["corn", "butter", "salt"] },
  { name: "Cornbread", ingredients: ["cornmeal", "flour", "milk", "egg"] },
  { name: "Buttermilk Cornbread", ingredients: ["cornmeal", "buttermilk", "butter"] },
  { name: "Coleslaw", ingredients: ["cabbage", "carrot", "mayonnaise", "vinegar"] },
  { name: "Potato Salad", ingredients: ["potato", "mayonnaise", "egg", "mustard"] },
  { name: "Macaroni Salad", ingredients: ["macaroni", "mayonnaise", "celery", "onion"] },
  { name: "Cobb Salad", ingredients: ["lettuce", "chicken", "bacon", "egg", "avocado"] },
  { name: "Garden Salad", ingredients: ["lettuce", "tomato", "cucumber", "dressing"] },
  { name: "Caesar Salad", ingredients: ["romaine", "parmesan", "croutons", "dressing"] },
  { name: "Waldorf Salad", ingredients: ["apple", "celery", "walnuts", "mayonnaise"] },
  { name: "Baked Beans", ingredients: ["beans", "molasses", "bacon", "onion"] },
  { name: "Collard Greens", ingredients: ["collard greens", "bacon", "onion"] },
  { name: "Succotash", ingredients: ["corn", "lima beans", "butter"] },
  { name: "Deviled Eggs", ingredients: ["egg", "mayonnaise", "mustard", "paprika"] },
  { name: "Nachos", ingredients: ["tortilla chips", "cheese", "beans", "jalapeno"] },
  { name: "Seven Layer Dip", ingredients: ["beans", "sour cream", "cheese", "avocado"] },
  { name: "Buffalo Chicken Dip", ingredients: ["chicken", "cream cheese", "hot sauce"] },
  { name: "Guacamole", ingredients: ["avocado", "lime", "onion", "cilantro"] },
  { name: "Chicken Fried Steak", ingredients: ["beef cutlet", "flour", "milk", "oil"] },
  { name: "Biscuits", ingredients: ["flour", "butter", "buttermilk"] },
  { name: "Dinner Rolls", ingredients: ["flour", "yeast", "milk", "butter"] },
  { name: "Stuffing", ingredients: ["bread", "celery", "onion", "broth"] },
  { name: "Cranberry Sauce", ingredients: ["cranberry", "sugar", "orange"] },
  { name: "Apple Pie", ingredients: ["apple", "flour", "butter", "cinnamon"] },
  { name: "Pumpkin Pie", ingredients: ["pumpkin", "egg", "cream", "cinnamon"] },
  { name: "Pecan Pie", ingredients: ["pecans", "corn syrup", "egg", "butter"] },
  { name: "Key Lime Pie", ingredients: ["lime", "condensed milk", "graham crackers"] },
  { name: "Cherry Cobbler", ingredients: ["cherry", "flour", "sugar", "butter"] },
  { name: "Peach Cobbler", ingredients: ["peach", "flour", "sugar", "butter"] },
  { name: "Apple Crisp", ingredients: ["apple", "oats", "brown sugar", "butter"] },
  { name: "Chocolate Chip Cookies", ingredients: ["flour", "butter", "chocolate chips", "sugar"] },
  { name: "Peanut Butter Cookies", ingredients: ["peanut butter", "sugar", "egg", "flour"] },
  { name: "Oatmeal Raisin Cookies", ingredients: ["oats", "raisins", "flour", "butter"] },
  { name: "Brownies", ingredients: ["chocolate", "butter", "sugar", "egg"] },
  { name: "Chocolate Cake", ingredients: ["flour", "cocoa", "sugar", "egg"] },
  { name: "Carrot Cake", ingredients: ["carrot", "flour", "cream cheese", "sugar"] },
  { name: "Cheesecake", ingredients: ["cream cheese", "graham crackers", "egg", "sugar"] },
  { name: "Banana Pudding", ingredients: ["banana", "vanilla pudding", "wafers", "cream"] },
  { name: "Rice Pudding", ingredients: ["rice", "milk", "sugar", "cinnamon"] },
  { name: "Bread Pudding", ingredients: ["bread", "milk", "egg", "sugar"] },
  { name: "Strawberry Shortcake", ingredients: ["strawberry", "biscuit", "cream"] },
  { name: "S'mores", ingredients: ["marshmallow", "chocolate", "graham crackers"] },
  { name: "Milkshake", ingredients: ["ice cream", "milk", "vanilla"] },
  { name: "Lemonade", ingredients: ["lemon", "sugar", "water"] },
  { name: "Iced Tea", ingredients: ["tea", "sugar", "lemon"] },
  { name: "Chicken Wrap", ingredients: ["chicken", "tortilla", "lettuce", "ranch"] },
  { name: "Veggie Burger", ingredients: ["beans", "breadcrumbs", "bun", "onion"] },
  { name: "Stuffed Peppers", ingredients: ["bell pepper", "ground beef", "rice", "tomato"] },
  { name: "Meatball Sub", ingredients: ["meatballs", "roll", "tomato sauce", "mozzarella"] },
  { name: "Pigs in a Blanket", ingredients: ["hot dog", "crescent dough"] },
  { name: "Chicken Enchiladas", ingredients: ["chicken", "tortilla", "enchilada sauce", "cheese"] },
  { name: "Taco Salad", ingredients: ["ground beef", "lettuce", "cheese", "tortilla chips"] },
  { name: "Burrito Bowl", ingredients: ["rice", "beans", "chicken", "salsa"] },
  { name: "Chili Cheese Fries", ingredients: ["potato", "chili", "cheese"] },
  { name: "Onion Rings", ingredients: ["onion", "flour", "buttermilk", "oil"] },
  { name: "Mozzarella Sticks", ingredients: ["mozzarella", "breadcrumbs", "egg", "oil"] },
  { name: "Popcorn Chicken", ingredients: ["chicken", "flour", "buttermilk", "oil"] },
  { name: "Fried Green Tomatoes", ingredients: ["green tomato", "cornmeal", "oil"] },
  { name: "Hush Puppies", ingredients: ["cornmeal", "onion", "buttermilk", "oil"] },
  { name: "Egg Fried Rice", ingredients: ["rice", "egg", "peas", "soy sauce"] },
  { name: "Beef and Broccoli", ingredients: ["beef", "broccoli", "soy sauce", "garlic"] },
  { name: "Sheet Pan Chicken and Veggies", ingredients: ["chicken", "potato", "broccoli", "olive oil"] },
  { name: "Slow Cooker Chicken Tacos", ingredients: ["chicken", "salsa", "tortilla"] },
  { name: "Turkey Meatballs", ingredients: ["ground turkey", "breadcrumbs", "egg", "parmesan"] },
  { name: "Ham and Cheese Sliders", ingredients: ["rolls", "ham", "cheese", "butter"] },
  { name: "Loaded Baked Potato Soup", ingredients: ["potato", "bacon", "cheese", "cream"] },
  { name: "Broccoli Cheddar Soup", ingredients: ["broccoli", "cheddar", "cream", "carrot"] },
  { name: "Beef Barley Soup", ingredients: ["beef", "barley", "carrot", "celery"] },
  { name: "Cabbage Roll Casserole", ingredients: ["cabbage", "ground beef", "rice", "tomato"] },
  { name: "Zucchini Bread", ingredients: ["zucchini", "flour", "sugar", "egg"] },
  { name: "Grilled Corn Salad", ingredients: ["corn", "tomato", "lime", "cilantro"] },
  { name: "Apple Sauce", ingredients: ["apple", "sugar", "cinnamon"] },
  { name: "Overnight Oats", ingredients: ["oats", "yogurt", "milk", "berries"] },
  { name: "Yogurt Parfait", ingredients: ["yogurt", "granola", "berries", "honey"] },
  { name: "Smoothie Bowl", ingredients: ["banana", "berries", "yogurt", "granola"] },
];

export const AMERICAN_TITLES: string[] = AMERICAN_RECIPES.map((r) => r.name);

const AMERICAN_TITLE_SET = new Set(AMERICAN_TITLES.map((t) => t.toLowerCase()));

export function isAuthenticAmericanTitle(title: string) {
  return AMERICAN_TITLE_SET.has(title.trim().toLowerCase());
}

/** Best American dish match for a set of ingredients. */
export function closestAmerican(ingredients: string[]) {
  const wanted = ingredients.map((i) => i.trim().toLowerCase()).filter(Boolean);
  if (wanted.length === 0) return undefined;
  let best: { name: string; score: number } | undefined;
  for (const r of AMERICAN_RECIPES) {
    const pool = [...r.ingredients, r.name].map((x) => x.toLowerCase());
    const hits = wanted.filter((w) => pool.some((p) => p.includes(w) || w.includes(p))).length;
    if (hits === 0) continue;
    if (!best || hits > best.score) best = { name: r.name, score: hits };
  }
  return best?.name;
}
